// Phase 8.6.1 — Enrichment Batch 9 (tools 81–90)
import { readFileSync, writeFileSync } from 'fs';
const PATH = './data/tools.json';
const tools = JSON.parse(readFileSync(PATH, 'utf8'));

const enrichment = {

    'consensus': {
        long_description: `<p>Consensus is an AI-powered search engine explicitly designed for academic research. Unlike general search engines like Google that index the entire internet—and thus return blogs, opinion pieces, and SEO spam—Consensus exclusively searches a massive database of peer-reviewed scientific papers.</p><p>Its primary function is to answer questions by surfacing direct evidence. When a user queries a topic (e.g., "Does creatine improve cognitive function?"), Consensus deploys large language models to read the abstracts and findings of thousands of relevant papers, synthesizing a direct answer and displaying a "Consensus Meter" that visually aggregates whether the scientific literature leans yes, no, or possibly.</p><p>It is widely adopted by academics, medical professionals, students, and fact-checkers who need to quickly ascertain the scientific consensus on a topic without manually reading dozens of dense academic abstracts.</p>`,
        how_it_works: `<p>A user types a scientific or factual question into the search bar. The engine retrieves relevant peer-reviewed papers from its database. It then uses language models to extract the specific conclusions from those papers related directly to the user\'s query. It generates a top-level summary paragraph citing multiple papers, displays the Consensus Meter (e.g., 70% Yes, 20% No, 10% Unsure), and lists the individual source papers below with the extracted, highlighted relevant quote from each abstract.</p>`,
        workflows: [
            { title: 'Medical Claim Verification', description: 'Healthcare journalists researching a new supplement check Consensus to see if the claims are backed by peer-reviewed human trials, ignoring marketing blogs.' },
            { title: 'Academic Literature Reviews', description: 'Graduate students begin their theses by asking broad questions, using the tool to instantly gather a foundational reading list of the most highly cited papers on the topic.' },
            { title: 'Fact-Checking Popular Science', description: 'General users query common health or nutrition myths, easily seeing a visual meter aggregating what the actual scientific community has published on the issue.' },
            { title: 'Drafting Research Proposals', description: 'Researchers use the "Synthesize" feature to generate quick, cited background paragraphs establishing the current state of knowledge for grant applications.' }
        ],
        feature_groups: [
            { title: 'Search & Synthesis', items: ['Exclusive peer-reviewed database', 'Natural language question answering', 'Consensus Meter aggregation', 'AI-generated summary paragraphs'] },
            { title: 'Academic Tools', items: ['Direct citation extraction', 'Filters for human/animal trials', 'Study design indicators (e.g., Meta-Analysis)', 'Integration with Copilot for document writing'] }
        ],
        best_for: ['Academics and graduate students', 'Medical and science journalists', 'Fact-checkers and researchers', 'Anyone seeking evidence-backed answers over internet opinions'],
        pros: ['Eliminates SEO spam and opinion blogs entirely from search results', 'The Consensus Meter provides an incredibly fast visual gut-check on a topic', 'Extracts the exact relevant sentence from dense abstracts, saving hours of reading time', 'High reliability due to exclusive sourcing from Semantic Scholar\'s database'],
        cons: ['Cannot answer questions outside of published scientific literature', 'AI syntheses can sometimes misinterpret deeply nuanced or highly conflicting data', 'Requires a premium subscription for unlimited AI summaries', 'Focuses heavily on abstracts rather than full-text deep reading (like Elicit)'],
        pricing_overview: `<p>Consensus offers a free tier with unlimited basic searches but strict limits on "AI Summaries" and the "Consensus Meter" features. The Premium subscription provides unlimited AI features, advanced study filters, and bookmarking capabilities. There are specific discounts for students and academic institutions.</p>`,
        comparison_summary: `<p>Consensus competes most directly with Elicit, Perplexity, and Google Scholar. Google Scholar is a massive database but lacks AI synthesis entirely, requiring manual reading. Perplexity is a fantastic general web search engine, but its Pro Search still occasionally pulls from non-peer-reviewed sources. Elicit is more complex, designed for deep methodological data extraction across columns. Consensus distinguishes itself as the absolute fastest, most user-friendly way to get a yes/no/maybe answer directly from peer-reviewed science.</p>`
    },

    'elicit': {
        long_description: `<p>Elicit is an AI research assistant designed specifically for deep academic literature review and data extraction. Built originally by the non-profit research lab Ought, Elicit automates the most labor-intensive parts of the academic research process: finding relevant papers, extracting specific data points across methodologies, and organizing findings into structured tables.</p><p>While standard AI search engines might summarize an abstract, Elicit is built to dig deeper. It allows researchers to upload their own PDFs or search a massive corpus of open-access papers, and then command the AI to extract highly specific data—such as "population size," "dosage," or "p-values"—from dozens of papers simultaneously.</p><p>It is the tool of choice for systematic reviewers, medical researchers, and PhD candidates who need to strictly evaluate the methodologies and outcomes of large sets of scientific literature.</p>`,
        how_it_works: `<p>A user enters a research question. Elicit searches its database of papers (via Semantic Scholar) and generates a structured table. Each row is a paper, and columns display data extracted by the AI. Users can add custom columns by typing questions (e.g., "What was the demographic of the control group?"). The AI reads the full text of the papers (when available) to populate that column. Users can also upload a batch of proprietary PDFs for the AI to analyze in the same tabular format.</p>`,
        workflows: [
            { title: 'Systematic Reviews', description: 'Medical researchers evaluating dozens of clinical trials use Elicit to automatically extract sample sizes, intervention types, and outcome metrics into a downloadable CSV.' },
            { title: 'Methodology Sourcing', description: 'Scientists designing an experiment search for similar past studies, specifically adding columns to extract the "limitations" and "equipment used" to avoid repeating past mistakes.' },
            { title: 'Literature Matrix Construction', description: 'Graduate students upload a folder of 50 assigned PDFs; Elicit generates an annotated bibliography matrix summarizing the core thesis and findings of each document.' },
            { title: 'Intervention Comparison', description: 'Policy analysts upload government reports to extract and compare the economic outcomes of different historical interventions across multiple jurisdictions.' }
        ],
        feature_groups: [
            { group: 'Search & Extraction', items: ['Tabular data extraction', 'Custom AI column generation', 'Full-text paper analysis', 'Semantic literature search'] },
            { group: 'Document Management', items: ['Upload and analyze personal PDFs', 'Chat with specific papers', 'Export tables to CSV/RIS', 'Highlight tracking back to source text'] }
        ],
        best_for: ['Researchers conducting systematic reviews', 'Medical and hard science doctoral candidates', 'Policy analysts synthesizing large reports', 'Scientists needing to extract methodologies'],
        pros: ['Unrivaled at extracting specific data points into structured, comparative tables', 'Allows analysis of private, uploaded PDFs not just the public database', 'Highly transparent, showing exactly where it found the data in the original text', 'Massively reduces the manual labor of building literature matrices'],
        cons: ['Steeper learning curve than simple Q&A search engines', 'AI extraction accuracy varies depending on how obscure the requested data point is', 'Full-text extraction is limited by open-access availability unless PDFs are uploaded', 'Pricing is based on a credit system, which can be difficult to predict for large reviews'],
        pricing_overview: `<p>Elicit operates via a credit system. The Basic free plan provides a small monthly allowance of credits for light searching. The Plus and Pro subscriptions provide significantly more credits, allow for the export of results, and enable high-volume PDF uploads and extraction tasks.</p>`,
        comparison_summary: `<p>Elicit\'s primary competitors are Consensus, Perplexity, and traditional reference managers like Mendeley. Consensus is better for asking a simple question and getting a broad scientific "yes/no/maybe" summary. Perplexity is better for general web research. Elicit differentiates itself powerfully by focusing on tabular data extraction—it is essentially an AI that builds systematic review spreadsheets for researchers based on deep reading of methodologies.</p>`
    },

    'fathom': {
        long_description: `<p>Fathom is an AI-powered meeting assistant designed to record, transcribe, highlight, and summarize video conference calls on platforms like Zoom, Google Meet, and Microsoft Teams. It operates as an unobtrusive bot that joins calls to handle all note-taking responsibilities, allowing participants to focus entirely on the conversation.</p><p>Fathom separates itself in a crowded market through its aggressive focus on simplicity and its completely free core product for individuals. It emphasizes real-time highlighting: users can click a button during a call to flag a moment, and Fathom automatically extracts that specific clip and transcript section into a neat summary afterward.</p><p>It is heavily adopted by sales professionals, customer success managers, and remote teams who need to sync meeting outcomes directly into CRM platforms (like Salesforce or HubSpot) without manual data entry.</p>`,
        how_it_works: `<p>A user installs the Fathom app or browser extension. When a Zoom, Meet, or Teams call begins, the Fathom bot automatically requests to join (providing mandatory recording consent notices to participants). During the call, Fathom transcribes the dialogue in real-time. The user has a side panel with buttons (e.g., "Action Item", "Insight", "Positive"). Clicking a button flags the current conversation. After the call, an AI generates a structured summary, and the flagged highlights are packaged as shareable video clips.</p>`,
        workflows: [
            { title: 'Automated Sales Handoffs', description: 'Account executives record discovery calls; Fathom automatically summarizes the client\'s pain points and pushes the notes and a video clip directly into the corresponding Salesforce record.' },
            { title: 'Customer Success Onboarding', description: 'CSMs record training sessions with new clients; they use Fathom to generate a playlist of specific feature explanations from the call to send back to the client as a tutorial.' },
            { title: 'Engineering Standup Summaries', description: 'Product managers have Fathom record daily standups, automatically generating a bulleted list of daily blockers and action items pushed directly to a Slack channel.' },
            { title: 'Interview Playback', description: 'Recruiters highlight specific answers during candidate interviews; hiring managers can watch those 30-second highlight clips rather than reviewing the entire 45-minute interview video.' }
        ],
        feature_groups: [
            { group: 'Recording & Transcription', items: ['Bot integration (Zoom, Meet, Teams)', 'Real-time multi-language transcription', 'Live highlighting tags', 'Automatic AI meeting summaries'] },
            { group: 'Sharing & Integration', items: ['Deep CRM synchronization (HubSpot, Salesforce)', 'Shareable video clips and playlists', 'Slack and Zapier integrations', 'Team-wide searchable meeting repository'] }
        ],
        best_for: ['Sales and customer success teams using CRMs', 'Remote managers conducting frequent 1-on-1s', 'Recruiters conducting multiple daily interviews', 'Individuals seeking a free, high-quality meeting recorder'],
        pros: ['The core recording and transcription product for individuals is 100% free with no limits', 'CRM integrations are seamless and automatic', 'Live highlighting buttons prevent the need to review the entire transcript later', 'Provides localized recording consent warnings to maintain compliance'],
        cons: ['Requires a visible bot to join the call, which some external clients may find intrusive', 'Audio quality relies heavily on the constraints of the conferencing software connection', 'Advanced team analytics require expensive enterprise plans', 'Not ideal for highly confidential board meetings where local recording (like Krisp) is preferred'],
        pricing_overview: `<p>Fathom offers an immensely popular Free tier for individuals that provides unlimited recording, transcription, and summarization. Paid Team Edition plans provide team-wide searchable repositories, advanced strict CRM syncing, unified billing, and conversational analytics for sales coaching.</p>`,
        comparison_summary: `<p>Fathom competes directly with Otter.ai, Fireflies.ai, and native tools like Zoom AI Companion. Fireflies offers slightly more robust developer APIs and custom conversational intelligence tracking for large sales teams. Otter is excellent for general transcription and university lectures. Fathom differentiates by offering the best completely free individual tier on the market, combined with an extremely intuitive live-highlighting UI that appeals perfectly to individual sales and success reps.</p>`
    },

    'frase': {
        long_description: `<p>Frase (Frase.io) is an AI-powered SEO and content optimization platform designed specifically for content marketers and SEO agencies. Unlike general AI writers that simply generate text from a prompt, Frase is engineered to reverse-engineer Google search results, ensuring the content written is mathematically optimized to rank for specific keywords.</p><p>It acts as a bridge between SEO research and content creation. It analyzes the top 20 Google results for any given search query to extract the exact headings, keyword frequencies, and topics covered by competitors. It then provides a real-time scoring editor that grades a writer's draft against those metrics.</p><p>With the integration of generative AI, Frase allows users to not only outline and optimize articles but to generate the actual paragraphs directly within the optimization editor, creating a highly streamlined SEO content factory workflow.</p>`,
        how_it_works: `<p>A user enters a target keyword (e.g., "Best CRM for real estate"). Frase scrapes the top Google results and generates a Research panel detailing the average word count, headings used, and overlapping topics. The user utilizes AI to auto-generate a comprehensive article outline based on competitor headings. They then write (or use the AI writer to generate) the content in the central editor. A dynamic score from 0-100 updates in real-time as the text incorporates semantic keywords suggested by the platform.</p>`,
        workflows: [
            { title: 'SEO Content Brief Generation', description: 'Content managers use Frase to instantly analyze the SERP and generate detailed structural briefs containing required headings and keywords to hand off to freelance human writers.' },
            { title: 'Legacy Content Refreshing', description: 'SEO specialists import declining blog posts into the editor; Frase highlights missing semantic keywords that competitors recently added, guiding the writer on how to update the post to regain rankings.' },
            { title: 'End-to-End AI Drafting', description: 'Niche site builders use Frase to scrape the SERP, auto-generate an optimized outline, and use the AI writer to draft the entire article section-by-section before publishing.' },
            { title: 'Competitor Gap Analysis', description: 'Strategists analyze a specific competitor\'s URL against their own to quickly identify which sub-topics the competitor covers that their own page lacks.' }
        ],
        feature_groups: [
            { group: 'SEO Research', items: ['Real-time SERP scraping', 'Competitor heading analysis', 'Semantic keyword extraction', 'Content brief generation'] },
            { group: 'Content Creation', items: ['Real-time SEO scoring editor', 'AI outline generation', 'AI paragraph/article writing', 'Content gap heatmaps'] }
        ],
        best_for: ['SEO agencies scaling content production', 'In-house content marketing teams', 'Niche website builders and affiliate marketers', 'Freelance writers needing to prove SEO optimization to clients'],
        pros: ['The real-time SEO scoring is highly accurate and gamifies the writing process', 'Automated brief generation saves hours of manual SERP research', 'Integrates AI generation directly into the optimization workflow seamlessly', 'Excellent for identifying semantic LSI (Latent Semantic Indexing) keywords'],
        cons: ['The AI writer, while good for SEO, can sometimes feel generic without human editing', 'Pricing can be complex, often requiring a base plan plus an "AI Add-on" for unlimited generation', 'Interface can feel overwhelming for non-SEO professionals', 'Does not provide off-page SEO metrics (like backlink data) found in Ahrefs'],
        pricing_overview: `<p>Frase offers tiered subscription plans based on the number of articles optimized per month. An additional monthly "Pro Add-On" is generally required to unlock unlimited AI writing generation and premium SEO data volume, making it an ongoing investment for professional teams.</p>`,
        comparison_summary: `<p>Frase competes heavily with Surfer SEO, MarketMuse, and general AI writers like Jasper. Jasper is a better pure creative writer but lacks native deep SERP extraction. MarketMuse is aimed at massive enterprise content strategy. Surfer SEO is Frase\'s most direct rival; Surfer is often considered to have slightly deeper keyword correlation data, but Frase generally offers a smoother, more integrated AI writing and outlining workflow natively within its editor.</p>`
    },

    'marketmuse': {
        long_description: `<p>MarketMuse is an enterprise-level content intelligence and strategy platform. Utilizing AI and machine learning, it analyzes a company's entire website against massive topic models to identify gaps in content authority, rather than just optimizing single pages for single keywords.</p><p>Instead of relying on search volume data like traditional SEO tools, MarketMuse builds personalized topic models to show a brand where they lack "topical authority" compared to competitors. It provides predictive metrics indicating how difficult it will be for a specific domain to rank for a specific topic based on their existing content footprint.</p><p>It is predominantly used by large enterprise marketing teams, major publishers, and high-end SEO agencies who need to build comprehensive, multi-year content strategies and cluster architectures rather than just writing individual blog posts.</p>`,
        how_it_works: `<p>A marketing director connects their website to MarketMuse. The platform inventories every page and analyzes the semantic relationships of their content. Using the "Inventory" dashboard, it highlights "Content Gaps"—topics related to their industry that competitors cover but they do not. The platform assigns a "Personalized Difficulty" score (how hard it will be for *this specific site* to rank). Teams then use the "Optimize" application to write content, scoring the draft against sophisticated semantic topic models.</p>`,
        workflows: [
            { title: 'Content Cluster Strategy', description: 'Editorial directors identify a core "Pillar" topic and use MarketMuse to automatically generate a list of 20 related cluster topics they must write about to establish domain authority in that niche.' },
            { title: 'Personalized Ranking Prediction', description: 'SEO teams stop chasing high-volume keywords they realistically cannot win; instead, they use Personalized Difficulty to target topics where their specific domain already has a competitive advantage.' },
            { title: 'Enterprise Content Auditing', description: 'Operations teams run a domain-wide audit; the AI identifies hundreds of "thin" or underperforming pages, automatically prioritizing which pages to update first for the fastest ROI.' },
            { title: 'Executive Briefs', description: 'Strategists generate highly detailed content briefs containing mandatory semantic topics, suggested word counts, and internal linking strategies to hand off to enterprise writing teams.' }
        ],
        feature_groups: [
            { group: 'Strategy & Auditing', items: ['Domain-wide content inventory', 'Personalized keyword difficulty scoring', 'Topical authority analysis', 'Content gap and cluster identification'] },
            { group: 'Optimization & Execution', items: ['Semantic topic modeling editor', 'Automated content briefs', 'Internal linking recommendations', 'Competitor content heatmaps'] }
        ],
        best_for: ['Enterprise content marketing departments', 'Large-scale digital publishers and media companies', 'High-end SEO strategy agencies', 'Teams focusing on topical authority over volume keyword chasing'],
        pros: ['The concept of "Personalized Difficulty" is unique and highly accurate for predicting ranking success', 'Peerless capability for analyzing entire domains to build topical authority clusters', 'Content briefs are incredibly detailed and data-driven', 'Moves teams away from vanity search volumes toward strategic content planning'],
        cons: ['Extremely expensive, strictly targeted at enterprise budgets', 'Steep learning curve required to understand its proprietary metrics and strategic philosophy', 'Not an AI content generator; it focuses on strategy and optimization over automated writing', 'Overkill for small businesses or individual bloggers'],
        pricing_overview: `<p>MarketMuse relies heavily on enterprise pricing. While they occasionally offer a highly limited free tier or standard plan for smaller agencies, the core value of the platform (domain-wide inventory and personalized metrics) is locked behind Premium enterprise contracts that cost thousands of dollars annually.</p>`,
        comparison_summary: `<p>MarketMuse competes in the optimization space with Surfer SEO, Clearscope, and Frase, but acts at a much higher strategic level. While Frase and Surfer are tactical tools excellent for optimizing a single article to rank today, MarketMuse is a strategic platform designed to analyze thousands of pages and tell a CMO exactly what 50 articles they need to write over the next six months to command a specific industry niche.</p>`
    },

    'copysmith': {
        long_description: `<p>Copysmith (now part of the larger Copysmith platform umbrella merging with tools like Frase and Rytr) is an AI copywriting software historically built with a very strong focus on e-commerce, enterprise marketing, and high-volume product descriptions.</p><p>Unlike general-purpose writers, Copysmith was designed to integrate deeply with e-commerce infrastructure (like Shopify, WooCommerce, and standard PIM catalogs). Its core value proposition is the ability to ingest a massive spreadsheet of SKU data (product names, dimensions, raw features) and automatically generate thousands of unique, SEO-optimized product descriptions simultaneously.</p><p>It acts primarily as an operational scaling tool for retail brands, marketing agencies, and large storefronts who need to deploy massive amounts of conversion-focused copy across vast inventories without relying on armies of freelance copywriters.</p>`,
        how_it_works: `<p>Users log into the dashboard and select a template (e.g., Product Description, Facebook Ad, SEO Meta Tag). For high-volume workflows, an e-commerce manager uploads a CSV file containing hundreds of product SKUs and their basic features. The user configures the desired tone of voice and target keywords. Copysmith processes the batch, using AI to write a unique, stylistic paragraph for every single product, which can then be bulk-exported or synced directly back into a Shopify storefront via integration.</p>`,
        workflows: [
            { title: 'Bulk E-commerce Catalog Generation', description: 'Retailers launching a new seasonal catalog upload a spreadsheet of 500 clothing items; Copysmith generates unique, SEO-friendly product descriptions for all 500 items in minutes.' },
            { title: 'A/B Testing Ad Copy', description: 'Marketing agencies use the platform to rapidly generate dozens of variations of Facebook and Google Ad headlines for a single client to run extensive A/B tests.' },
            { title: 'Direct Shopify Syncing', description: 'Store owners utilize the Shopify native app integration to click a button within their Shopify dashboard, instantly generating and publishing new copy for a product page.' },
            { title: 'Team Brand Governance', description: 'Enterprise teams lock in specific "Brand Voices" and terminology rules, ensuring that all copy generated by Junior marketers adheres strictly to corporate tone guidelines.' }
        ],
        feature_groups: [
            { group: 'E-commerce Scaling', items: ['Bulk CSV copy generation', 'Direct Shopify & WooCommerce integrations', 'Product description templates', 'Catalog manager tools'] },
            { group: 'Enterprise Workflow', items: ['Team collaboration and approval workflows', 'Plagiarism checking built-in', 'Custom Brand Voice tuning', 'API access for custom integrations'] }
        ],
        best_for: ['E-commerce store owners and retail brands', 'Marketing agencies managing massive ad campaigns', 'Enterprise marketing teams requiring brand voice controls', 'SEO managers needing to optimize thousands of product pages'],
        pros: ['The bulk generation capabilities via CSV upload are massive time-savers for large stores', 'Deep, native integrations with e-commerce platforms like Shopify', 'Strong team collaboration features for enterprise approval workflows', 'Historically more reliable for strict product copy than highly creative general AI writers'],
        cons: ['Less suited for long-form creative storytelling or deep narrative blogging', 'The platform direction has been turbulent due to corporate acquisitions and product merging', 'Pricing can be steep for small businesses needing massive bulk generation limits', 'User interface can feel utilitarian compared to modern, sleek alternatives'],
        pricing_overview: `<p>Copysmith offers tiered subscriptions. The Starter tier focuses on individual marketers. The Pro tier unlocks bulk generation, robust integrations, and team features. Enterprise plans provide custom API access, custom templates, and dedicated account management for massive retail operations.</p>`,
        comparison_summary: `<p>Copysmith competes with Jasper, Anyword, and Writesonic. Jasper is vastly superior for long-form content, blog posts, and versatile creative writing. Anyword focuses heavily on predictive performance scoring for ads. Copysmith\'s primary differentiator remains its historical focus on massive scale e-commerce: specifically, the ability to effortlessly ingest a spreadsheet of 10,000 SKUs and bulk-generate optimized product descriptions, a workflow where other tools often fail or require tedious manual prompting.</p>`
    },

    'hyperwrite': {
        long_description: `<p>HyperWrite is an AI-powered writing assistant that operates primarily as a ubiquitous Chrome extension, bringing generative capabilities, autocompletion, and personalized writing assistance directly into the browser environments where users already work (Gmail, Google Docs, LinkedIn, etc.).</p><p>Rather than requiring users to log into a separate dashboard to generate text and safely paste it elsewhere, HyperWrite "reads" the context of the page the user is currently on. It offers sentence-by-sentence predictive text (similar to advanced Gmail Smart Compose) and the ability to command generation directly within text boxes.</p><p>Furthermore, HyperWrite has aggressively expanded into autonomous AI agent territory, introducing features where the AI can actually execute actions in the browser on the user's behalf, such as researching a topic, buying a product, or booking a flight.</p>`,
        how_it_works: `<p>A user installs the HyperWrite Chrome extension. As they type an email in Gmail or a post on LinkedIn, the AI analyzes the user\'s historical writing style and the context of the current draft, projecting suggested sentence completions in gray text; the user hits Tab to accept. Alternatively, the user can open the HyperWrite sidebar to use specific tools (like a summarizer or rewriter). For agent tasks, a user types "Order a pepperoni pizza to my address," and the AI opens a new tab, navigating the web visually to execute the instruction.</p>`,
        workflows: [
            { title: 'In-Context Email Drafting', description: 'Professionals drafting complex responses in Outlook Web or Gmail use the inline autocompletion to write emails 50% faster, with the AI matching their personal tone.' },
            { title: 'Social Media Ghostwriting', description: 'Executives writing thought leadership posts directly in the LinkedIn text box use the extension to expand brief notes into fully formatted, engaging posts.' },
            { title: 'Autonomous Web Research (Agent)', description: 'Users command the HyperWrite Agent to "Find the top 5 CRM tools, compare their pricing, and put it in a Google Doc." The AI visually navigates the web natively to execute the multi-step task.' },
            { title: 'Document Rewriting', description: 'Students or writers highlight a paragraph in Google Docs and use the extension popup to instantly rewrite it to be more persuasive, professional, or concise.' }
        ],
        feature_groups: [
            { group: 'Writing Assistance', items: ['Ubiquitous Chrome extension', 'Personalized context-aware autocomplete', 'In-browser templates and generators', 'Custom document rewriting'] },
            { group: 'Autonomous Agents', items: ['Web navigation automation', 'Task execution via natural language', 'Automated research gathering', 'Multi-step browser actions'] }
        ],
        best_for: ['Professionals prioritizing workflow speed in existing apps', 'Heavy Gmail, LinkedIn, and Google Docs users', 'Early adopters interested in autonomous AI browser agents', 'Users wanting a personalized AI writer rather than generic output'],
        pros: ['Eliminates the friction of copy-pasting between dashboards by working directly where you type', 'Personalized AI learns the user\'s specific voice over time', 'The autonomous browser agent feature is bleeding-edge technology', 'Extremely convenient for daily email triage'],
        cons: ['Requires granting a Chrome extension permission to read web data, which poses privacy concerns for enterprise users', 'Autonomous agents are still experimental and can fail or get confused on complex websites', 'Less suited for generating structured, multi-page SEO content compared to dedicated editors', 'Can occasionally conflict with other browser spellcheck or grammar extensions (like Grammarly)'],
        pricing_overview: `<p>HyperWrite offers a limited free tier providing basic access to autocomplete and generation tools. The Premium tier offers unlimited usage, advanced personalized AI models, and priority access. An Ultra tier is available for power users requiring the highest level of autonomous agent capabilities and context memory.</p>`,
        comparison_summary: `<p>HyperWrite competes with GrammarlyGO, Monica, and Wordtune. GrammarlyGO is deeply integrated but focuses heavily on correctness and tone refinement. Monica is a powerful sidebar wrapper for various models. HyperWrite differentiates itself significantly with its "TypeAhead" personalized autocomplete (acting like a massively upgraded Gmail Smart Compose everywhere on the web) and its ambitious pivot into building true autonomous browser agents capable of operating the web for the user.</p>`
    },

    'anyword': {
        long_description: `<p>Anyword is an AI copywriting platform designed exclusively for data-driven marketing teams. While most AI writers focus on generating fluent text, Anyword specifically generates text engineered to maximize conversion rates, backed by a proprietary predictive performance scoring engine.</p><p>Before a user publishes an ad or an email, Anyword analyzes the drafted copy against a vast database of historical marketing campaigns. It assigns a "Predictive Performance Score," estimating how likely the copy is to engage the target demographic compared to variants. This allows marketers to make data-backed decisions on copy rather than relying on creative intuition.</p><p>It is predominantly targeted at performance acquisition marketers, digital advertising agencies, and corporate marketing teams managing large spending budgets across Facebook, Google, and email channels.</p>`,
        how_it_works: `<p>A marketer creates a project for a Facebook Ad campaign. They input the product details and target demographic. Anyword generates several variations of the ad copy. Beside each variation is a "Predictive Performance Score" (e.g., 85/100), along with a demographic panel predicting how it will perform among specific age groups or genders based on historical data. Marketers can connect their actual ad accounts, allowing Anyword to train its custom AI model on the brand\'s specific past successes and failures for future generation.</p>`,
        workflows: [
            { title: 'Performance Ad Copy Variation', description: 'Acquisition marketers generate 20 variations of a Google Search ad, selecting the top 3 with the highest predictive scores to run in their A/B testing budget, eliminating the guesswork.' },
            { title: 'Subject Line Optimization', description: 'Email marketers test their drafted newsletter subject lines in the Anyword engine, using the AI to suggest tweaks that predictively increase open rates by 15%.' },
            { title: 'Custom Brand Model Training', description: 'Enterprise teams connect their Facebook Ads Manager account; Anyword reads years of past campaign data to automatically learn exactly what vocabulary actually drives ROI for that specific brand.' },
            { title: 'Landing Page Copy Scoring', description: 'Growth hackers paste existing landing page headlines into the tool; the AI scores them and generates higher-performing alternatives designed to lower bounce rates.' }
        ],
        feature_groups: [
            { group: 'Performance Generation', items: ['Predictive Performance Scoring', 'Demographic-specific copy prediction', 'Ad platforms templates (FB, Google, LinkedIn)', 'Landing page and email optimization'] },
            { group: 'Data Integration', items: ['Custom model training on user ad accounts', 'Brand voice management', 'Continuous campaign performance monitoring', 'Enterprise SSO and team collaboration'] }
        ],
        best_for: ['Performance and acquisition marketers managing ad budgets', 'Digital advertising and media buying agencies', 'Email marketing specialists optimizing open rates', 'Enterprise marketing teams seeking data-backed copy decisions'],
        pros: ['The predictive performance score completely shifts copy generation from subjective art to objective data', 'Connecting existing ad accounts creates an incredibly powerful, custom-trained brand AI', 'Demographic breakdown predictions are unique and valuable for targeted media buying', 'Reduces wasted ad spend on poorly performing creative tests'],
        cons: ['Pricing is significantly higher than general-purpose AI writers, targeting enterprise budgets', 'Less versatile for creative fiction, broad blogging, or non-commercial writing', 'Requires a fundamental trust in the proprietary scoring algorithm', 'The interface is highly data-dense, which may overwhelm casual users'],
        pricing_overview: `<p>Anyword operates strictly as a premium marketing tool. Plans (Starter, Data-Driven) are tiered based on features, with the defining predictive scoring and account-integration features reserved for higher tiers. Enterprise plans provide custom models and dedicated support for large marketing departments.</p>`,
        comparison_summary: `<p>Anyword competes with Jasper, Copy.ai, and Copysmith. Jasper and Copy.ai are vastly superior for general marketing, blog writing, and creative brainstorming across a wide organization. Copysmith excels at bulk e-commerce catalog generation. Anyword distinguishes itself entirely through its Predictive Performance Scoring and the ability to train its AI directly on a brand\'s live ad data. It is less of a creative writing assistant and more of a mathematical copy-optimization engine for media buyers.</p>`
    },

    '10web': {
        long_description: `<p>10Web is an AI-powered website builder platform constructed entirely around the WordPress ecosystem. It aims to solve the historic friction of WordPress—complex hosting setups, difficult theme building, and slow page speeds—by automating the entire process using generative AI and specialized cloud hosting.</p><p>Its marquee feature is an AI website generator that functions as a structural cloning and building tool. Users can prompt the AI to build a business website from scratch, or they can input the URL of any existing website. The AI analyzes the layout, structure, and design of the target URL and recreates it as a fully editable, optimized WordPress site built on the Elementor page builder.</p><p>It is designed for freelance web developers, digital agencies, and small business owners who want the ultimate flexibility and ownership of WordPress without the traditional development headaches.</p>`,
        how_it_works: `<p>A user signs up and provides a prompt describing their business, or pastes a competitor\'s URL. The 10Web AI analyzes the request, generates relevant written content, creates stock images, and builds the visual layout. Within minutes, a fully functioning WordPress site is spun up on 10Web\'s Google Cloud hosting. The user can then edit any part of the site visually using the integrated Elementor drag-and-drop builder, while 10Web\'s backend engines automatically optimize the site to achieve 90+ Google PageSpeed scores.</p>`,
        workflows: [
            { title: 'Rapid WordPress Prototyping', description: 'Web design agencies drastically reduce client turnaround time by prompting the AI to generate a functional baseline website in minutes, which they then customize rather than building from a blank theme.' },
            { title: 'Legacy Site Recreation', description: 'Business owners migrate off closed platforms like Wix by feeding their Wix URL into 10Web, which automatically clones the design into an editable WordPress environment they fully own.' },
            { title: 'Automated PageSpeed Optimization', description: 'Site owners migrate their sluggish existing WordPress sites to 10Web hosting; the platform\'s automated booster minifies CSS, defers JavaScript, and optimizes images to fix Core Web Vitals automatically.' },
            { title: 'SEO Optimized Content Population', description: 'Freelancers use the integrated AI assistant inside the WordPress dashboard to generate SEO-optimized blog posts and product descriptions directly into the CMS.' }
        ],
        feature_groups: [
            { group: 'AI Building', items: ['AI URL cloning to WordPress', 'Generative site creation from prompts', 'AI text and image generation', 'Integrated Elementor editing'] },
            { group: 'Hosting & Performance', items: ['Automated Google PageSpeed optimization', 'Google Cloud enterprise hosting', 'Automated backups and security', '1-click malware removal'] }
        ],
        best_for: ['Web design agencies scaling client production', 'Small business owners wanting WordPress without the technical setup', 'Freelancers migrating client sites to faster hosting', 'Users looking to recreate designs from closed platforms'],
        pros: ['The URL cloning feature is incredibly powerful for migrating site layouts', 'Maintains the infinite flexibility and plugin ecosystem of true WordPress', 'Automated PageSpeed optimization actually delivers on 90+ score promises', 'Eliminates the painful setup phase of traditional WordPress hosting'],
        cons: ['Users must manage their sites specifically within the Elementor builder framework', 'While it attempts to simplify WordPress, the underlying CMS can still overwhelm total beginners compared to Squarespace', 'Migrating extremely complex custom-coded sites via URL clone may require manual fixing', 'Pricing is structured as a SaaS hosting model, not a one-time theme purchase'],
        pricing_overview: `<p>10Web operates on a bundled SaaS model incorporating AI generation, hosting, and the PageSpeed booster. Pricing is tiered (Personal, Premium, Agency) based on the number of websites hosted and monthly visitor volume. Separate standalone plans exist specifically for the PageSpeed optimization tool for sites hosted elsewhere.</p>`,
        comparison_summary: `<p>10Web competes with Durable, Hostinger AI Builder, and traditional WordPress hosting (like WP Engine). Durable and Hostinger generate simpler, proprietary websites very quickly but lock users into closed ecosystems. 10Web differentiates itself by offering the speed of AI generation while outputting into the open-source, infinitely extensible WordPress ecosystem. It operates in a unique niche: AI building tools bolted seamlessly onto managed WordPress hosting.</p>`
    },

    'durable': {
        long_description: `<p>Durable is an AI website builder and comprehensive "business in a box" platform designed specifically for solo entrepreneurs and service-based small businesses (like landscapers, consultants, or independent contractors). Its primary claim to fame is the ability to generate a fully functioning, professional website with images, copy, and a contact form in under 30 seconds.</p><p>Unlike complex visual builders that require design skills, Durable restricts users to highly curated, block-based designs. It prioritizes extreme speed to market over granular pixel-pushing. Furthermore, it integrates a lightweight CRM, invoicing tools, and an AI assistant into the dashboard, attempting to replace the need for multiple software subscriptions for a new business.</p><p>It targets absolute beginners who find platforms like WordPress or even Squarespace too complicated or time-consuming, focusing solely on getting a business online and capturing leads instantly.</p>`,
        how_it_works: `<p>A user visits the Durable homepage, enters their business type (e.g., "Roofing"), and their location. Within seconds, the AI generates a multi-section website featuring localized SEO copy, relevant stock imagery, services lists, testionials, and a functional lead capture form. The user enters a lightweight editor to regenerate specific sections (by clicking "regenerate"), edit text, or swap colors based on simple palettes. Once published, any leads captured by the site are funneled into the built-in CRM dashboard.</p>`,
        workflows: [
            { title: 'Instant Local Service Launch', description: 'A newly certified plumber enters their trade and city; Durable generates a localized, SEO-ready website in 30 seconds, allowing them to start sharing a professional link immediately.' },
            { title: 'Automated Lead Management', description: 'Small business owners receive customer inquiries through the generated site form; Durable\'s built-in CRM tracks the lead, and the integrated AI drafts a professional email reply quoting services.' },
            { title: 'Promotional Campaign Generation', description: 'Consultants use the internal AI marketing assistant to instantly generate Google Ads copy and Facebook posts linking back to their new Durable site.' },
            { title: 'Integrated Business Operations', description: 'Freelancers manage their entire digital presence natively, sending automated invoices to clients from the same dashboard that hosts their portfolio website.' }
        ],
        feature_groups: [
            { group: 'Website Generation', items: ['Under 30-second AI site generation', 'Location-based SEO copy', 'Automated stock media integration', 'Regenerate-by-section editing'] },
            { group: 'Business Operations', items: ['Integrated CRM for lead capture', 'Invoicing and payment tools', 'AI marketing copy generation', 'Custom domain management'] }
        ],
        best_for: ['Solo entrepreneurs launching their first business', 'Local service providers (trades, consultants, cleaners)', 'Non-technical users intimidated by traditional website builders', 'Users needing an all-in-one suite (Site, CRM, Invoicing)'],
        pros: ['Arguably the fastest way to get a functional, good-looking business site online', 'The all-in-one approach (CRM + Invoicing) saves a solo founder hundreds of dollars in disparate software', 'Extremely low learning curve; impossible to "break" the design', 'Copy generation is well-tuned for localized service businesses'],
        cons: ['Highly restrictive design capabilities; you cannot drag-and-drop elements freely', 'Not suitable for complex e-commerce, large SaaS sites, or custom web apps', 'Vendor lock-in: sites cannot be exported to other hosts', 'SEO capabilities are basic, lacking the depth needed for highly competitive national campaigns'],
        pricing_overview: `<p>Durable operates on a straightforward SaaS subscription model. Plans (Starter, Business) are billed monthly or annually and include website hosting, custom domain connection, the AI assistant, and the CRM/invoicing tools. It positions itself as a single flat fee replacing multiple subscriptions.</p>`,
        comparison_summary: `<p>Durable competes with Squarespace, Wix, and 10Web. 10Web builds scalable WordPress sites that require some tech literacy. Squarespace and Wix offer brilliant templates but require hours of manual drag-and-drop design and copywriting to launch. Durable differentiates itself by trading granular design control for absolute maximum speed to launch, and by bundling operational software (CRM, invoicing) specifically tailored for solo service businesses into a single dashboard.</p>`
    }

};

let patched = 0;
let modified = [];
for (const tool of tools) {
    if (enrichment[tool.id]) {
        Object.assign(tool, enrichment[tool.id]);
        patched++;
        modified.push(tool.id);
    }
}
writeFileSync(PATH, JSON.stringify(tools, null, 2));
console.log(`Batch 9 complete. Patched ${patched} tools: ${modified.join(', ')}`);
