// Phase 8.6 — Enrichment Batch 2 (tools 11–20)
// Run: node scripts/enrich-batch-2.mjs
import { readFileSync, writeFileSync } from 'fs';

const PATH = './data/tools.json';
const tools = JSON.parse(readFileSync(PATH, 'utf8'));

const enrichment = {

    'jasper-ai': {
        long_description: `<p>Jasper is an AI writing platform tailored for marketing and content teams. It provides tools for generating blog posts, ad copy, social media content, product descriptions, and other marketing materials. Originally launched as Jarvis in 2021, it rebranded to Jasper and expanded its feature set substantially as the AI writing market matured.</p><p>Jasper is designed for marketing professionals and agencies who need to produce large volumes of content at speed. It offers templated workflows for common content formats, tone controls, and brand voice configuration, making it easier for teams to maintain consistency across output.</p><p>In a market increasingly filled with AI writing tools, Jasper differentiates on its marketing-specific features, team collaboration functionality, and integrations with tools like Surfer SEO and Google Ads.</p>`,
        how_it_works: `<p>Users start from a template or blank document within the Jasper editor. They provide context such as brand name, product detail, target audience, and tone, then prompt the AI to generate content. The editor supports iterative generation — users can regenerate sections, adjust tone, or instruct Jasper to expand or shorten content. Jasper Brand Voice allows users to upload existing content so the model can match their established writing style. Team collaboration features allow multiple editors to work within shared projects.</p>`,
        workflows: [
            { title: 'Blog Post Production', description: 'Marketing teams use Jasper to produce SEO-oriented blog drafts from topic briefs, then edit and refine the output before publishing.' },
            { title: 'Ad Copy Generation', description: 'Agencies use Jasper to generate multiple ad variants across platforms like Google, Facebook, and LinkedIn from a single product brief.' },
            { title: 'Brand Voice Consistency', description: 'Content teams configure Jasper Brand Voice to ensure all AI-generated output matches the established tone and language of their brand.' },
            { title: 'Product Description Scaling', description: 'E-commerce teams use Jasper to generate product descriptions at scale, covering large product catalogues without proportional writing resource investment.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Blog post and article generation', 'Ad copy and headline writing', 'Social media content generation', 'Tone and style controls', 'Content templates for common formats'] },
            { group: 'Advanced Capabilities', items: ['Brand Voice training on existing content', 'Surfer SEO integration', 'Team collaboration and workflows', 'Campaign management view', 'Image generation via Jasper Art'] }
        ],
        best_for: ['Marketing teams producing high-volume content', 'Digital agencies managing multiple brand voices', 'E-commerce businesses with large product catalogues', 'Content managers overseeing distributed writing teams', 'Paid advertising specialists'],
        pros: ['Marketing-specific templates and workflows', 'Brand Voice feature for consistent output', 'Team collaboration built in', 'Integration with SEO tools', 'Broad content format coverage'],
        cons: ['Higher price point than general AI assistants', 'Output still requires human editing', 'Brand Voice requires training on sufficient existing content', 'Less versatile outside marketing use cases', 'Quality varies with prompt specificity'],
        pricing_overview: `<p>Jasper is available on a per-seat subscription basis. Plans are tiered by feature access, including the number of brand voices, seats, and access to advanced workflow features. Enterprise plans offer custom pricing, dedicated support, and API access. There is no permanent free tier, though trial periods are typically offered.</p>`,
        comparison_summary: `<p>Jasper competes most directly with Copy.ai and Writesonic in the AI marketing copy space. Compared to ChatGPT, it offers a more structured, marketing-focused experience but at a higher price. For teams needing SEO integration, Jasper's Surfer SEO partnership gives it an advantage over Copy.ai. For general writing purposes, Grammarly and Notion AI are more accessible and affordable alternatives.</p>`
    },

    'canva-ai': {
        long_description: `<p>Canva AI refers to the suite of artificial intelligence features integrated into Canva, the widely used visual design platform. These features include text-to-image generation (Magic Media), AI-powered background removal (Magic Eraser), AI photo editing (Magic Edit), text-to-presentation generation, and AI-assisted copy writing tools.</p><p>Canva itself is used by over 150 million people for designing social media graphics, presentations, documents, marketing materials, and more. The AI layer was introduced progressively from 2022, making powerful design automation accessible to Canva's non-designer audience without requiring expertise in standalone AI tools.</p><p>Canva AI sits at the intersection of design software and generative AI, targeting business users, marketers, educators, and content creators who are already operating within the Canva ecosystem rather than AI-first tool adopters.</p>`,
        how_it_works: `<p>Canva AI features are accessed directly within the standard Canva design interface. Users can invoke tools such as Magic Media to generate images from text prompts, use Magic Eraser to remove objects from photos, or use the AI presentation generator to create full slide decks from a topic description. AI writing tools assist with headline and body copy generation within design elements. Most tools operate within the existing drag-and-drop Canva canvas without requiring a separate interface.</p>`,
        workflows: [
            { title: 'Social Media Template Personalisation', description: 'Marketers generate AI images and edit existing visuals within social media templates to produce on-brand content at speed.' },
            { title: 'Presentation Generation', description: 'Business professionals describe a topic and let Canva AI generate a structured presentation with slides, headings, and placeholder content.' },
            { title: 'Product Image Editing', description: 'E-commerce teams use Magic Eraser and Magic Edit to clean up product photographs and replace backgrounds without external photo editing tools.' },
            { title: 'Marketing Collateral Production', description: 'Small businesses use Canva AI to produce flyers, posters, and social graphics without a design budget or external agency.' }
        ],
        feature_groups: [
            { group: 'Core AI Features', items: ['Magic Media text-to-image generation', 'Magic Eraser (object removal)', 'Magic Edit (AI photo editing)', 'AI text-to-presentation', 'AI writing assistant for copy'] },
            { group: 'Advanced Capabilities', items: ['Brand Kit enforcement with AI outputs', 'Translate designs to multiple languages', 'Magic Animate for auto-animated presentations', 'Bulk AI content generation', 'AI-powered resize for multiple formats'] }
        ],
        best_for: ['Non-designers producing marketing and social media content', 'Small business owners managing their own brand materials', 'Educators and students creating visual presentations', 'Marketing teams at SMBs', 'Social media managers'],
        pros: ['Integrated into a tool millions already use', 'Low barrier to entry for non-designers', 'Broad range of AI features across design, image, and copy', 'Regular feature additions', 'Strong template library complements AI outputs'],
        cons: ['AI image quality is below specialist tools like Midjourney', 'Most advanced AI features require Canva Pro', 'Less control over AI output compared to dedicated tools', 'Canva AI is dependent on the overall Canva platform', 'Not designed for high-fidelity professional design outputs'],
        pricing_overview: `<p>Many Canva AI features are available on the free Canva plan with usage limits. Full access to tools like Magic Media, Magic Eraser, and Magic Edit requires Canva Pro, which is a monthly or annual subscription per seat. Canva Teams and Canva Enterprise plans extend AI features across organisations with additional management capabilities.</p>`,
        comparison_summary: `<p>Canva AI's advantage is its integration within an existing, widely adopted design tool. For image generation quality, Midjourney and Adobe Firefly produce superior results. For dedicated design work, Adobe Creative Cloud with Firefly is more capable. Canva AI is most appropriate for users who are already in Canva and want AI augmentation within that workflow, rather than users seeking a standalone AI image or design tool.</p>`
    },

    'stable-diffusion': {
        long_description: `<p>Stable Diffusion is an open-source text-to-image generative AI model developed and released by Stability AI in 2022. Unlike closed commercial models, Stable Diffusion model weights are publicly available, enabling anyone to run the model locally, fine-tune it, or build on top of it.</p><p>This open nature has made Stable Diffusion the foundation for a large ecosystem of community-developed tools, interfaces, fine-tuned model variants (LoRAs, checkpoints), and derivative applications. It is used by independent artists, researchers, developers, and commercial teams who require customisation or data privacy that cloud-hosted tools cannot provide.</p><p>Stable Diffusion is accessible through interfaces like AUTOMATIC1111, ComfyUI, and InvokeAI for local use, or through hosted platforms like DreamStudio (Stability AI's own commercial interface) and third-party services.</p>`,
        how_it_works: `<p>Users provide a text prompt and optionally a reference image. The diffusion model generates an image by iteratively refining random noise guided by the prompt. Users can control output through parameters including steps, guidance scale, seed, and sampler. Local installations allow full control over model checkpoints, LoRA adaptors, and generation pipeline. Cloud-hosted versions abstract these controls into a simpler interface. Fine-tuned models trained on specific styles or subjects can be swapped in to alter output characteristics.</p>`,
        workflows: [
            { title: 'Custom Style Fine-Tuning', description: 'Artists and studios fine-tune Stable Diffusion on their own artwork to create a personalised model that generates images in a defined aesthetic style.' },
            { title: 'Privacy-Sensitive Commercial Imagery', description: 'Businesses running local instances use Stable Diffusion to generate product imagery and design concepts without transmitting data to external cloud services.' },
            { title: 'Research and Model Experimentation', description: 'Researchers use Stable Diffusion as a base model for AI image research, exploring new training techniques, sampling methods, and fine-tuning approaches.' },
            { title: 'Batch Image Production', description: 'Developers build automated pipelines on top of Stable Diffusion to generate large volumes of images for training datasets, game assets, or marketing materials.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Text-to-image generation', 'Image-to-image transformation', 'Inpainting and outpainting', 'Multiple sampler and scheduler options', 'Seed-based reproducibility'] },
            { group: 'Advanced Capabilities', items: ['LoRA and checkpoint fine-tuning', 'ControlNet for pose and composition control', 'DreamBooth personalisation', 'Local installation with full hardware control', 'Open-source ecosystem integrations'] }
        ],
        best_for: ['Developers and machine learning researchers', 'Artists wanting full control over image generation', 'Organisations with data privacy requirements', 'Creators wanting to fine-tune models on personal art styles', 'Studios building custom AI image pipelines'],
        pros: ['Fully open-source and locally runnable', 'No per-image API cost when run locally', 'Massive community of tools, models, and fine-tunes', 'Highest degree of customisation of any major image model', 'No content policy restrictions in a local environment'],
        cons: ['Requires technical knowledge to set up locally', 'Output quality depends heavily on model version and configuration', 'Local hardware requirements (GPU recommended)', 'Community model quality varies considerably', 'No centralised support structure'],
        pricing_overview: `<p>The Stable Diffusion model weights are free to download and use locally. Running the model on personal hardware incurs no per-generation cost beyond electricity. DreamStudio, Stability AI's hosted interface, uses a credit-based pricing model. Various third-party platforms built on Stable Diffusion set their own pricing structures. Enterprise licensing is available through Stability AI for commercial applications.</p>`,
        comparison_summary: `<p>Stable Diffusion's primary differentiation from Midjourney and DALL-E 3 is its open-source, locally-runnable nature. Midjourney produces more consistently polished aesthetic output out of the box. DALL-E 3 has better prompt adherence. Stable Diffusion offers the highest level of customisation and privacy. For users without technical setup requirements, Midjourney or Canva AI are more accessible alternatives.</p>`
    },

    'dall-e-3': {
        long_description: `<p>DALL-E 3 is an image generation model developed by OpenAI, released in 2023. It represents a significant update over previous DALL-E versions, with substantially improved prompt adherence, coherence, and detail accuracy. DALL-E 3 is accessible directly through ChatGPT with image generation enabled and through OpenAI's API.</p><p>The model is designed to generate images that closely match the nuances of a text prompt, including accurate rendering of spatial relationships, text within images, and multi-subject compositions. It is particularly noted for its ability to generate readable text inside generated images, a capability where earlier models struggled significantly.</p><p>DALL-E 3 targets a broad audience — from casual users accessing it via ChatGPT to developers building image generation into applications via API — making it one of the most accessible image generation models in the market.</p>`,
        how_it_works: `<p>Users provide a text prompt describing the desired image, and DALL-E 3 generates an image matching the description. Within ChatGPT, the model automatically refines the user's prompt before generation to improve results. Via the API, developers pass prompts directly and receive image URLs in response. The model supports style modifiers, composition instructions, and descriptive detail. Image resolution and quality options can be configured via API parameters.</p>`,
        workflows: [
            { title: 'Marketing Visual Concept Creation', description: 'Marketing teams use DALL-E 3 via ChatGPT to generate concept images for campaigns, social media posts, and presentations during early creative stages.' },
            { title: 'Illustrated Content Production', description: 'Bloggers and newsletter writers use DALL-E 3 to generate custom illustrations for articles, avoiding generic stock photography.' },
            { title: 'Application Image Generation', description: 'Developers integrate DALL-E 3 via OpenAI API to add on-demand image generation features to applications and platforms.' },
            { title: 'Product Mockup Generation', description: 'Designers and start-ups use DALL-E 3 to produce product concept visuals and mockup images before investing in photography or 3D rendering.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Text-to-image generation', 'High-fidelity prompt adherence', 'Text rendering within images', 'Multiple image size options', 'Natural language prompt interpretation'] },
            { group: 'Advanced Capabilities', items: ['API integration for developers', 'Automatic prompt refinement in ChatGPT', 'HD quality generation option', 'Safety content-policy enforcement', 'Style and composition descriptors'] }
        ],
        best_for: ['Marketers generating visual concepts', 'Content creators needing custom illustrations', 'Developers building image generation into apps', 'Designers producing concept mockups', 'Casual users accessing through ChatGPT'],
        pros: ['Excellent literal prompt adherence', 'Can generate readable text within images', 'Accessible via ChatGPT without separate tooling', 'Straightforward API for developers', 'High output consistency across attempts'],
        cons: ['No fine-tuning or style-locking capability', 'Aesthetically less distinctive than Midjourney output', 'Per-image API cost at scale', 'Cannot edit or iterate on specific image regions', 'Content policy restricts some generation requests'],
        pricing_overview: `<p>DALL-E 3 is included in ChatGPT Plus, Pro, and Team subscriptions with a monthly generation limit. Via the OpenAI API, pricing is per-image based on resolution and quality setting. Higher resolution and HD quality options cost more per generation. There is no free tier for API usage, though ChatGPT Free users may have limited access depending on platform availability.</p>`,
        comparison_summary: `<p>DALL-E 3's primary advantage over Midjourney is its literal prompt following and text-in-image capability. Midjourney produces more artistically distinctive output and is preferred for visual concept work. Stable Diffusion offers far greater customisation but requires technical setup. Adobe Firefly better integrates with the Creative Cloud workflow. For users who already use ChatGPT, DALL-E 3 is the lowest-friction option for image generation.</p>`
    },

    'microsoft-copilot': {
        long_description: `<p>Microsoft Copilot is the AI assistant developed and distributed by Microsoft, built on OpenAI's GPT models. It operates as a general consumer AI assistant available via copilot.microsoft.com and is integrated into Windows, Bing, and Microsoft 365 applications including Word, Excel, PowerPoint, Teams, and Outlook.</p><p>Microsoft 365 Copilot (the enterprise-integrated variant) allows users to generate documents in Word, analyse data in Excel, create presentations in PowerPoint, and summarise meetings in Teams — all within their existing Microsoft productivity tools without switching to a standalone AI application.</p><p>Microsoft Copilot competes directly with Google Gemini in the enterprise productivity AI space, with both products leveraging their respective ecosystems (Microsoft 365 vs. Google Workspace) as their primary differentiation.</p>`,
        how_it_works: `<p>In consumer mode via copilot.microsoft.com or Windows, users interact with Copilot as a conversational assistant for general queries, content generation, and image creation. Within Microsoft 365, Copilot is accessed through toolbar buttons or slash commands within each application. In Word, it drafts and rewrites text. In Excel, it analyses data and generates formulas. In PowerPoint, it creates presentations from prompts. In Teams, it summarises meeting transcripts. All processing uses Microsoft's Azure OpenAI infrastructure.</p>`,
        workflows: [
            { title: 'Word Document Generation', description: 'Professionals prompt Copilot in Word to generate report drafts, policy documents, and meeting agendas from short text descriptions.' },
            { title: 'Excel Data Analysis', description: 'Analysts use Copilot in Excel to generate data summaries, apply formula suggestions, and create pivot tables from natural language requests.' },
            { title: 'Teams Meeting Summarisation', description: 'After meetings in Microsoft Teams, Copilot generates summaries, extracts action items, and answers questions about what was discussed.' },
            { title: 'PowerPoint Presentation Creation', description: 'Users describe a topic and Copilot generates a structured PowerPoint presentation with slide layouts, headings, and suggested content.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Conversational AI assistant', 'Web-connected responses', 'Image generation (via DALL-E)', 'Integrated into Windows and Bing', 'Microsoft 365 document and email features'] },
            { group: 'Microsoft 365 Capabilities', items: ['Word: document drafting and rewriting', 'Excel: data analysis and formula assistance', 'PowerPoint: presentation generation', 'Teams: meeting summarisation and Q&A', 'Outlook: email drafting and summarisation'] }
        ],
        best_for: ['Microsoft 365 enterprise users', 'Teams running meetings in Microsoft Teams', 'Knowledge workers producing reports and presentations', 'Organisations standardised on Windows and Office', 'IT-administered enterprise environments'],
        pros: ['Deep integration with Microsoft 365 applications', 'Enterprise-grade security and compliance through Microsoft', 'No separate AI tool required for M365 users', 'Strong meeting intelligence in Teams', 'Backed by OpenAI model quality'],
        cons: ['Microsoft 365 Copilot requires additional per-user licensing', 'Quality can vary between applications', 'Consumer Copilot is less capable than the enterprise M365 variant', 'Heavy dependency on existing Microsoft infrastructure', 'Limited customisation compared to standalone AI tools'],
        pricing_overview: `<p>Microsoft Copilot is available for free in consumer mode via copilot.microsoft.com and Windows. Microsoft 365 Copilot, which integrates with Word, Excel, PowerPoint, Teams, and Outlook, requires an additional per-user per-month licence on top of an existing Microsoft 365 subscription. Enterprise agreements can bundle Microsoft 365 Copilot with other Microsoft services.</p>`,
        comparison_summary: `<p>Microsoft Copilot's primary competitor in enterprise productivity is Google Gemini for Workspace. The choice often comes down to whether an organisation uses Microsoft 365 or Google Workspace as their primary productivity suite. For standalone AI assistant use, ChatGPT and Claude offer more flexibility. For code-specific use, GitHub Copilot (a separate product) is more capable than general Copilot.</p>`
    },

    'cursor': {
        long_description: `<p>Cursor is an AI-first code editor built as a fork of Visual Studio Code. It is developed by Anysphere and designed from the ground up to integrate AI coding assistance deeply into the editing experience, going beyond the extension-based model of tools like GitHub Copilot.</p><p>Unlike Copilot, which operates as a VS Code extension, Cursor is a standalone editor that treats AI as a native component of the development environment. It supports inline code generation, multi-file edits, codebase-aware conversations, and AI-driven debugging — all from within the editor interface.</p><p>Cursor is primarily targeted at software developers who want the most integrated AI coding experience available, particularly those working on complex codebases where cross-file context and AI reasoning are required.</p>`,
        how_it_works: `<p>Cursor uses the VS Code interface with AI deeply embedded. The Tab key accepts AI completions similar to Copilot. The Cmd+K shortcut opens an inline prompt for generating or editing code within the current file. The sidebar chat allows developers to ask questions about the codebase, request multi-file refactors, and get debugging assistance with full project context. Cursor indexes the codebase to enable AI responses that reference specific files, functions, and patterns across the project.</p>`,
        workflows: [
            { title: 'Codebase-Aware Question Answering', description: 'Developers ask Cursor questions about their own codebase — "where is the auth middleware applied?" — and receive accurate answers based on indexed project files.' },
            { title: 'Multi-File Refactoring', description: 'Engineers request refactors that span multiple files, such as renaming a function used across a project, and Cursor applies the changes with a single confirmation.' },
            { title: 'Test Generation from Implementation', description: 'Developers highlight a function and ask Cursor to generate corresponding unit tests, with the AI using project context to produce relevant assertions.' },
            { title: 'Bug Diagnosis and Fix', description: 'When debugging, developers paste error messages into Cursor Chat or use the inline AI to receive targeted fix suggestions with project-specific context.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['AI inline code completion (Tab)', 'Inline code generation and editing (Cmd+K)', 'Chat with codebase context', 'Supports multiple underlying AI models', 'All VS Code extensions compatible'] },
            { group: 'Advanced Capabilities', items: ['Codebase indexing for context-aware responses', 'Multi-file edit mode (Composer)', 'Custom agent rules (.cursorrules)', 'Privacy mode for local code', 'Model selection including Claude and GPT-4'] }
        ],
        best_for: ['Full-stack and backend developers', 'Teams working on complex multi-file codebases', 'Developers who want deeper AI integration than extensions provide', 'Engineers evaluating AI coding tools for team adoption', 'Developers comfortable picking a dedicated AI editor'],
        pros: ['Deepest AI-editor integration currently available', 'Codebase indexing enables accurate context-aware answers', 'Multi-file edits reduce manual navigation', 'Compatible with existing VS Code extensions', 'Supports multiple frontier models'],
        cons: ['Requires adopting a new editor rather than extending an existing one', 'Subscription cost on top of existing tooling', 'Codebase indexing may not support very large monorepos well', 'AI suggestions still require developer review', 'Distinct from GitHub Copilot — switching may disrupt team preference'],
        pricing_overview: `<p>Cursor offers a free tier with limited monthly AI completions and chat queries. The Pro plan provides substantially higher limits and access to faster models. Business plans add team management, privacy controls, and audit logging. Pricing is per-seat on a monthly or annual basis.</p>`,
        comparison_summary: `<p>Cursor's primary competitor is GitHub Copilot, which operates as a VS Code extension rather than a standalone editor. Cursor offers deeper codebase awareness and multi-file editing, while Copilot benefits from GitHub integration. Replit AI targets a different audience (beginners and cloud-based development). For developers who want to stay within VS Code specifically, Copilot with Copilot Chat is the more compatible choice.</p>`
    },

    'synthesia': {
        long_description: `<p>Synthesia is an AI video generation platform that creates videos using AI avatars that deliver spoken content from a text script. Users write a script, select an AI avatar and voice, and the platform generates a professional-quality talking-head video without cameras, actors, or studio equipment.</p><p>Founded in 2017 and headquartered in London, Synthesia is primarily used by enterprise learning and development teams, corporate communications departments, and marketing organisations that need to produce video content at scale without the traditional production overhead.</p><p>It is one of the most established platforms in the AI video avatar market, offering over 100 AI avatars and supporting 120+ languages, making it particularly relevant for multilingual training and communication content.</p>`,
        how_it_works: `<p>Users create a new video project in the Synthesia web interface, write or paste a script, and select from available AI avatars and voice options. The platform synthesises the video by animating the avatar to deliver the script with appropriate lip sync and expression. Users can add slides, screen recordings, images, and background music. Finished videos are rendered in the cloud and can be shared via link or exported as MP4 files. Custom AI avatars can be created from an approved recorded video of a real person.</p>`,
        workflows: [
            { title: 'Employee Onboarding Video Production', description: 'HR and L&D teams produce onboarding and training videos using Synthesia, replacing costly live video shoots with script-driven avatar productions.' },
            { title: 'Multilingual Training Localisation', description: 'Global organisations use Synthesia to produce training content in multiple languages simultaneously by changing script language and voice, without re-recording.' },
            { title: 'Product Update Communications', description: 'Product teams create internal product update videos quickly from written release notes without coordinating film crews or presenter schedules.' },
            { title: 'Personalised Sales Videos', description: 'Sales teams use Synthesia to produce personalised prospect videos at scale, customising scripts per recipient while reusing the same avatar and format.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Script-to-video with AI avatars', '100+ built-in AI avatars', '120+ language and voice support', 'Slide and media layer integration', 'Video export and sharing'] },
            { group: 'Advanced Capabilities', items: ['Custom personal AI avatar creation', 'Screen recording integration', 'Brand kit with colours and logos', 'API access for programmatic video generation', 'Analytics on video viewing'] }
        ],
        best_for: ['L&D and HR teams producing training content', 'Enterprise communications teams', 'Global organisations needing multilingual video', 'Marketing teams scaling video production', 'Sales teams creating personalised video outreach'],
        pros: ['Eliminates camera and studio requirements for talking-head video', 'Strong multilingual support', 'Consistent quality across large video volumes', 'Custom avatar option for brand authenticity', 'Enterprise-grade reliability and security'],
        cons: ['Avatars retain an artificial quality visible to attentive viewers', 'Custom avatar creation requires a recorded video submission and approval process', 'Less suitable for live-action, narrative, or highly dynamic video', 'API access is not available on all plans', 'Per-video or credit costs can add up at high volumes'],
        pricing_overview: `<p>Synthesia offers a free tier for limited personal use with restricted avatar and video options. Paid plans are priced per seat per month and increase the number of videos, avatar choices, and advanced features such as custom avatars and analytics. Enterprise plans offer custom pricing, API access, and dedicated account support.</p>`,
        comparison_summary: `<p>Synthesia's primary competitors in the AI avatar video space are HeyGen and D-ID. HeyGen has gained notable traction with real-time video translation features. D-ID targets more developer-focused use cases via API. For general video generation without avatars, Runway and Pika are different category tools. Synthesia differentiates on enterprise readiness, avatar variety, and multilingual production capabilities.</p>`
    },

    'heygen': {
        long_description: `<p>HeyGen is an AI video generation platform that produces talking avatar videos from text scripts, similar in category to Synthesia. HeyGen gained significant market attention in 2023 for its video translation feature, which can dub existing video content — including the speaker's voice and lip movements — into other languages using AI.</p><p>It is used by content creators, marketing teams, e-learning producers, and sales professionals who need to create professional video without camera equipment or studio production. HeyGen offers a library of AI avatars, voice cloning, and customisable video templates.</p><p>HeyGen has positioned itself as a more innovation-forward alternative in the AI avatar video space, with frequent new feature releases and a growing user base across both consumer and business markets.</p>`,
        how_it_works: `<p>Users create videos by selecting an avatar, entering a script, choosing a language and voice, and submitting for rendering. The platform animates the avatar to deliver the script with matching lip sync. For video translation, users upload an existing video and select a target language — HeyGen generates a dubbed version with translated audio and re-animated lip movements. Video output can be downloaded or shared via link.</p>`,
        workflows: [
            { title: 'Multilingual Video Dubbing', description: 'Content creators upload English-language videos and use HeyGen to produce dubbed versions in other languages with matched lip sync, expanding audience reach.' },
            { title: 'Sales Personalisation at Scale', description: 'Sales teams generate personalised video messages by customising scripts per prospect while reusing the same avatar, reducing recording time while maintaining a personal touch.' },
            { title: 'E-Learning Module Production', description: 'Training teams produce course videos using AI avatars and screen recordings, removing the need for presenter-on-camera recording sessions.' },
            { title: 'Social Media Content Production', description: 'Creators and agencies use HeyGen to produce talking-head style social media content quickly from written scripts.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Script-to-video with AI avatars', 'AI video translation and dubbing', '100+ built-in avatars', 'Voice cloning', 'Multiple language support'] },
            { group: 'Advanced Capabilities', items: ['Real-time avatar interactions', 'Custom avatar creation from video', 'API access for automation', 'Template library', 'Video analytics'] }
        ],
        best_for: ['Content creators expanding to multilingual audiences', 'Marketing and sales teams scaling video output', 'E-learning and training content producers', 'Agencies managing video production at volume', 'Individual creators building a faceless video channel'],
        pros: ['Video translation with lip sync is a notable differentiator', 'Active feature development with frequent releases', 'Accessible to non-technical users', 'Competitive avatar quality', 'Strong API for developer integrations'],
        cons: ['Avatar realism is detectable on close viewing', 'Video translation accuracy varies by language pair', 'Custom avatar creation requires submitted video approval', 'Free tier is limited for practical use', 'Usage costs scale with video volume'],
        pricing_overview: `<p>HeyGen offers a free plan with limited monthly video credits. Paid plans increase monthly credit allowance, unlock higher resolution output, custom avatar creation, and API access. Enterprise plans provide custom credit packages, team management, and dedicated support. Credits are consumed per minute of video generated.</p>`,
        comparison_summary: `<p>HeyGen and Synthesia are the most directly comparable platforms in the AI avatar video space. Synthesia has a stronger enterprise presence and more formal security certifications. HeyGen's video translation with lip-sync feature differentiates it for multilingual content use cases. D-ID is more API-developer focused. For general content creators, HeyGen's pricing and interface make it accessible, while Synthesia tends to attract larger enterprise accounts.</p>`
    },

    'descript': {
        long_description: `<p>Descript is an AI-powered audio and video editing platform founded in 2017. It takes an unconventional approach to media editing — rather than requiring users to manipulate timelines and waveforms directly, Descript generates a text transcript of recorded audio or video, and editing is performed by editing the transcript text.</p><p>Users delete words from the transcript to cut them from the audio, rearrange sentences to restructure content, or use the AI to fill gaps and correct mistakes through Overdub, its voice synthesis feature. This makes Descript particularly accessible to podcast producers, YouTubers, and teams producing interview or documentary content who are more comfortable with text editing than traditional timeline-based tools.</p><p>Descript also includes screen recording, video publishing, and collaboration features, positioning it as a broader content production tool beyond a simple editor.</p>`,
        how_it_works: `<p>Users import or record audio or video files directly into Descript. The platform generates a text transcript using AI speech recognition. Editors work directly in the transcript — selecting and deleting text removes corresponding audio from the recording, enabling fast content cuts without timeline navigation. Filler words (ums, ahs, silences) can be automatically removed. Overdub allows users to correct mistakes by typing replacement words that are synthesised in the speaker's cloned voice. Finished content can be exported as audio, video, or published directly to platforms.</p>`,
        workflows: [
            { title: 'Podcast Editing via Transcript', description: 'Podcast editors cut filler words, restructure interview answers, and remove off-topic segments by editing the text transcript, dramatically reducing editing time.' },
            { title: 'Filler Word Removal', description: 'Content creators use Descript to automatically detect and remove filler words and long silences with a single click, improving audio quality without manual timeline scrubbing.' },
            { title: 'Video Content Repurposing', description: 'Teams export transcript text from long-form videos to create subtitles, article summaries, or newsletter content from the same recorded session.' },
            { title: 'Remote Interview Editing', description: 'Teams producing interview-based content record calls or in-person sessions, then use Descript to collaboratively edit content from the transcript without requiring co-location.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Transcript-driven audio and video editing', 'Automatic filler word and silence removal', 'Screen recording', 'Multi-track audio and video timeline', 'Subtitle and caption generation'] },
            { group: 'Advanced Capabilities', items: ['Overdub voice synthesis for mistake correction', 'AI green screen (background removal)', 'Collaborative editing', 'Direct publishing to podcast platforms', 'Video publishing and analytics'] }
        ],
        best_for: ['Podcast producers and editors', 'YouTubers and video content creators', 'Teams producing interview or conversation-based content', 'Educators creating recorded course content', 'Journalists producing audio and video stories'],
        pros: ['Transcript-based editing dramatically reduces edit time for spoken content', 'Automatic filler word removal', 'Accessible to non-technical editors', 'Strong collaborative features', 'All-in-one recording, editing, and publishing'],
        cons: ['Transcript accuracy depends on audio quality and accent clarity', 'Overdub voice cloning requires significant training audio', 'Not suitable for music, highly produced video, or motion graphics work', 'Export limitations on lower-tier plans', 'Can feel unfamiliar for editors accustomed to timeline-first tools'],
        pricing_overview: `<p>Descript offers a free plan with limited transcript and export capabilities. Paid plans increase transcript hours, remove watermarks, unlock Overdub and AI green screen features, and allow higher resolution exports. Team plans add shared projects, collaborative editing, and seat management. Billing is per-seat on a monthly or annual basis.</p>`,
        comparison_summary: `<p>Descript's transcript-first editing model is unique and differentiated from traditional tools like Adobe Premiere and Final Cut Pro. For podcast-specific editing, Hindenburg and Reaper are alternatives for users who prefer traditional waveform editing. For video only, CapCut and Premiere are more capable for cinematic work. Descript's strength is in spoken-word content — interviews, podcasts, educational videos — where the transcript approach saves substantial time.</p>`
    },

    'suno': {
        long_description: `<p>Suno is an AI music generation platform that creates full songs — including vocals, instrumentation, and lyrics — from a text prompt. Founded in 2022 and publicly launched in 2023, it rapidly gained a large user base due to its ability to generate surprisingly musical and coherent audio output across a wide range of genres.</p><p>Suno is used by content creators, game developers, video producers, and musicians exploring AI tools. It lowers the barrier to custom music production significantly — users without musical training can produce genre-appropriate background music or experimental song ideas in seconds.</p><p>It competes in the AI music generation space with tools like Udio, Soundraw, and Boomy, and has attracted both enthusiast and professional interest for its output quality relative to alternatives.</p>`,
        how_it_works: `<p>Users type a description of the desired song — specifying genre, mood, lyrical themes, or instrumentation — and Suno generates a full audio track, typically 60–90 seconds in length. Users can generate multiple variations from the same prompt, extend songs to continue beyond the initial clip, and remix or regenerate sections. Lyrics are generated automatically or can be provided by the user. Output is available for streaming and download within the platform.</p>`,
        workflows: [
            { title: 'Background Music for Video Content', description: 'Video creators and editors use Suno to generate royalty-structure music for use in YouTube videos, social reels, and presentations without licensing fees associated with commercial music.' },
            { title: 'Game and App Audio Prototyping', description: 'Indie game developers use Suno to quickly generate placeholder and concept music for game levels, menus, and cutscenes during the prototyping phase.' },
            { title: 'Creative Music Ideation', description: 'Musicians use Suno to rapidly explore genre crosses, chord progressions, and lyrical themes before developing more polished versions through traditional production tools.' },
            { title: 'Social Media Audio Content', description: 'Content creators produce short custom jingles and theme music for brand content, podcasts, and social media profiles.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Text-to-song generation (vocals + instruments)', 'Genre and mood specification', 'Custom lyric input', 'Multiple variation generation', 'Song extension'] },
            { group: 'Advanced Capabilities', items: ['Remix and regeneration controls', 'Download in audio formats', 'Style reference inputs', 'Playlist creation', 'API access (Pro plans)'] }
        ],
        best_for: ['Content creators needing royalty-free custom music', 'Indie game developers', 'Video producers and editors', 'Podcasters and brand audio producers', 'Musicians and songwriters exploring AI-assisted ideation'],
        pros: ['Surprisingly musical and coherent output for a generative tool', 'Fast generation from simple text prompts', 'Wide genre coverage', 'No musical training required', 'Song extension enables longer compositions'],
        cons: ['Commercial usage rights depend on subscription tier', 'Output quality and style adherence vary', 'Vocal quality can be inconsistent across languages and styles', 'Limited fine-grained control over instrumentation', 'Music generation AI regulations remain unsettled'],
        pricing_overview: `<p>Suno offers a free tier with a limited number of daily song generations. Paid plans increase monthly generation credits, unlock commercial usage rights, and provide access to features such as longer tracks and higher audio quality. Credits are consumed per song generation.</p>`,
        comparison_summary: `<p>Suno is most directly compared to Udio, which launched around the same time and offers similar capabilities. Soundraw and Beatoven.ai offer more structured music generation without lyrics, targeting background and mood music. Boomy is a more simplified tool for casual music creation. Suno differentiates on vocal quality and the breadth of song structure it can generate from a single prompt.</p>`
    }

};

let patched = 0;
const modified = [];

for (const tool of tools) {
    if (enrichment[tool.id]) {
        const data = enrichment[tool.id];
        for (const [key, val] of Object.entries(data)) {
            tool[key] = val;
        }
        patched++;
        modified.push(tool.id);
    }
}

writeFileSync(PATH, JSON.stringify(tools, null, 2));
console.log(`Batch 2 complete. Patched ${patched} tools: ${modified.join(', ')}`);
