// Phase 8.6 — Enrichment Batch 3 (tools 21–30)
import { readFileSync, writeFileSync } from 'fs';
const PATH = './data/tools.json';
const tools = JSON.parse(readFileSync(PATH, 'utf8'));

const enrichment = {

    'replit': {
        long_description: `<p>Replit is a cloud-based development environment that allows users to write, run, and share code directly in the browser without installing any local software. It supports over 50 programming languages and includes AI coding assistance (Replit AI) built directly into the editor.</p><p>Originally designed for students and beginners, Replit has expanded into a broader platform used by hobbyists, educators, and professional developers for prototyping, teaching, and hosting small-scale applications. Its zero-setup approach makes it particularly accessible for newcomers to programming.</p><p>Replit also functions as a social platform — users can share projects publicly, fork others' work, and collaborate in real-time, creating a community layer on top of the coding environment.</p>`,
        how_it_works: `<p>Users create a new project (called a "Repl") by selecting a language or template. The in-browser editor, file tree, terminal, and output console are all available without any local installation. Replit AI provides code completions, explains errors, and can generate entire project scaffolds from a natural language description. Projects run on Replit's cloud servers and can be shared via URL or deployed as always-on web services on paid plans.</p>`,
        workflows: [
            { title: 'Learning to Code Without Setup', description: 'Beginners open a language environment and start writing code immediately without installing compilers, package managers, or editors on their machine.' },
            { title: 'Rapid Prototyping', description: 'Developers prototype ideas or test API integrations in Replit without creating a local project, enabling quick exploration from any device.' },
            { title: 'Teaching and Classroom Use', description: 'Educators create coding assignments in Replit and share links with students, who can fork and complete the assignment in a controlled, browser-based environment.' },
            { title: 'AI-Assisted App Building', description: 'Users describe an application they want to build and use Replit AI to scaffold the full project, then iterate with AI suggestions.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Browser-based multi-language editor', 'Integrated terminal and console', 'Real-time collaboration', 'Project sharing via URL', 'Version control with Git integration'] },
            { group: 'Advanced Capabilities', items: ['Replit AI code generation and completion', 'Always-on deployments (paid)', 'Custom domains', 'Database integration', 'Mobile app support'] }
        ],
        best_for: ['Students and beginners learning programming', 'Educators running code-based courses', 'Developers prototyping ideas without local setup', 'Hobbyists building and hosting small projects', 'Teams needing a shared coding space without environment configuration'],
        pros: ['Zero-setup — runs entirely in browser', 'Supports a large number of programming languages', 'Strong educational community and resources', 'Real-time collaboration built in', 'AI code assistance integrated without external extensions'],
        cons: ['Performance is limited compared to local development for large projects', 'Always-on deployments require a paid plan', 'Free-tier projects may sleep after inactivity', 'Not suitable for resource-intensive or production-scale applications', 'Data privacy considerations for professional code'],
        pricing_overview: `<p>Replit offers a free tier with access to basic project creation, collaboration, and AI features within usage limits. Paid plans increase compute power, unlock always-on deployments, add private projects, and increase AI usage limits. Teams and education plans are also available for group and institutional use.</p>`,
        comparison_summary: `<p>Replit's main competitors are CodeSandbox and GitHub Codespaces in the browser-based coding environment space. GitHub Codespaces is more powerful and enterprise-ready but requires more setup. CodeSandbox focuses more on front-end and JavaScript frameworks. Replit's unique strength is its community, education focus, and the simplicity of going from zero to running code with no setup.</p>`
    },

    'figma': {
        long_description: `<p>Figma is a collaborative interface design tool that operates entirely in the browser and has become the industry standard for product design, UI/UX work, and design system management. Founded in 2012 and now owned by Adobe (announced acquisition in 2022, though subsequently abandoned), Figma is used by designers, product managers, engineers, and stakeholders across tech companies worldwide.</p><p>Figma introduced a real-time multiplayer collaboration model to the design tool space, allowing teams to work simultaneously on the same design file without the version conflict problems common to desktop-native tools. Its plugin ecosystem, component libraries, and developer handoff features made it a complete design-to-development pipeline tool.</p><p>Figma has incorporated AI features through its AI toolkit and acquired Diagram, an AI-focused design startup, to accelerate its AI roadmap.</p>`,
        how_it_works: `<p>Users create canvases within shared files in the Figma web editor. Designs are built from frames, components, and styles that can be shared across projects via libraries. Real-time collaboration allows multiple users to edit the same file simultaneously, with each person's cursor visible. Designers use components and auto-layout to build responsive designs systematically. Developers access design specs, export assets, and interact with the Dev Mode view to inspect code properties. Plugins extend functionality for tasks including content generation, icon insertion, and accessibility checks.</p>`,
        workflows: [
            { title: 'UI Component System Design', description: 'Design teams build shared component libraries in Figma that all product designers reference, ensuring visual consistency across a product suite.' },
            { title: 'Collaborative Wireframing and Prototyping', description: 'Product teams use Figma for early-stage wireframing and clickable prototype creation, enabling stakeholder feedback before development begins.' },
            { title: 'Design-to-Developer Handoff', description: 'Developers use Figma Dev Mode to inspect design specifications, extract CSS properties, and download assets directly from completed design files.' },
            { title: 'Design System Documentation', description: 'Design teams use Figma to document component usage, interaction patterns, and design tokens in a single shared source of truth.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Real-time collaborative vector design', 'Component and library system', 'Auto-layout for responsive design', 'Prototyping and interaction design', 'Developer handoff (Dev Mode)'] },
            { group: 'Advanced Capabilities', items: ['FigJam whiteboarding integration', 'Plugin ecosystem (thousands of plugins)', 'Variables and design tokens', 'AI-powered design features', 'Enterprise team management and access control'] }
        ],
        best_for: ['UI/UX designers at product companies', 'Product managers and teams building digital products', 'Front-end engineers requiring design specs', 'Design systems teams', 'Agencies managing multi-client design work'],
        pros: ['Real-time collaboration without version conflicts', 'Browser-based — no installation required', 'Industry-standard design tool with large community', 'Strong developer handoff with Dev Mode', 'Extensive plugin ecosystem'],
        cons: ['Can be slow with very large files or many users', 'Offline access is limited', 'Advanced features require Professional or Organisation plans', 'Learning curve for users new to design tools', 'Browser dependency can be a limitation in low-connectivity environments'],
        pricing_overview: `<p>Figma offers a free tier for individuals with up to three active files and unlimited personal projects. Professional plans are billed per editor per month and add unlimited files, shared libraries, and advanced prototyping. Organisation and Enterprise plans add design system management, SSO, and advanced admin controls.</p>`,
        comparison_summary: `<p>Figma's primary competitors are Sketch (Mac-only, desktop) and Adobe XD (discontinued in active development). Sketch remains popular among Mac-first design teams but lacks real-time collaboration. Penpot is an open-source alternative. Since Figma acquired the browser-first collaborative model, it has dominated the professional product design market. Adobe's Creative Cloud suite (Photoshop, Illustrator) targets different production design use cases rather than UI/UX specifically.</p>`
    },

    'adobe-firefly': {
        long_description: `<p>Adobe Firefly is Adobe's suite of generative AI models integrated into the Adobe Creative Cloud ecosystem. Launched in 2023, Firefly provides text-to-image generation, generative fill, text effects, and other AI-powered creative tools directly inside Adobe Photoshop, Illustrator, and Adobe Express.</p><p>A key differentiator for Firefly is Adobe's commitment to training the model on licensed content, including Adobe Stock images, to provide clearer commercial usage rights compared to models trained on broadly scraped web data. This positions it as suitable for professional commercial creative work.</p><p>Firefly is primarily targeted at existing Adobe Creative Cloud users who want to add AI image generation and editing capabilities to their established design workflows, rather than standalone AI image tool adopters.</p>`,
        how_it_works: `<p>In Photoshop, users select an area of an image and use Generative Fill to describe what should appear in that area — the AI generates multiple options that blend with the existing image context. Generative Expand allows users to extend the canvas and fill the new area with AI-generated content matching the original. In Illustrator, users generate vectors from text prompts. Adobe Express users access a simplified interface for generating images from text. All features are accessible via the Creative Cloud applications without a separate login.</p>`,
        workflows: [
            { title: 'Photoshop Object Removal and Replacement', description: 'Photo editors select unwanted elements in images and use Generative Fill to replace them with naturally blending AI-generated alternatives.' },
            { title: 'Background Extension for Repurposing', description: 'Designers extend product photographs to different aspect ratios using Generative Expand, generating natural-looking backgrounds for different format requirements.' },
            { title: 'Text Effects and Typography', description: 'Graphic designers apply AI-generated stylistic effects to text in Illustrator or Firefly web, creating illustrated typography without manual drawing.' },
            { title: 'Concept Image Generation in Creative Workflow', description: 'Art directors use Firefly inside Photoshop to generate visual concept options directly within their existing project files without switching to a separate tool.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Text-to-image generation', 'Generative Fill in Photoshop', 'Generative Expand for canvas extension', 'Vector illustration from text prompt', 'Text effects and stylisation'] },
            { group: 'Advanced Capabilities', items: ['Firefly Custom Models for brand-specific training', 'Integration across Creative Cloud suite', 'Commercial licence clarity from training approach', 'Structure and style reference inputs', 'Adobe Express AI for non-designers'] }
        ],
        best_for: ['Professional photographers and photo editors', 'Graphic designers working in Adobe Illustrator', 'Creative agencies with commercial image requirements', 'Adobe Creative Cloud users wanting AI augmentation', 'Brand and marketing teams producing visual content'],
        pros: ['Directly integrated into existing Creative Cloud workflows', 'Commercially safer training methodology', 'Generative Fill is a genuinely useful photo editing feature', 'Strong for extending and modifying existing images', 'Adobe brand trust for commercial clients'],
        cons: ['Output quality varies compared to standalone generators like Midjourney', 'Requires Creative Cloud subscription for full feature access', 'Custom Model training requires the enterprise plan', 'Less community-driven prompting culture than Midjourney', 'Standalone Firefly web experience is less capable than in-application integration'],
        pricing_overview: `<p>Adobe Firefly features are included in existing Creative Cloud subscription plans with a monthly generative credit allocation. Credits are consumed per generation. Additional credit bundles can be purchased. The standalone Firefly web interface is available separately with its own credit plan. Adobe Express plans include Firefly for non-Creative Cloud users.</p>`,
        comparison_summary: `<p>Adobe Firefly targets Creative Cloud users specifically, whereas Midjourney and DALL-E 3 serve a broader standalone audience. For commercial work where licensing provenance matters, Firefly's training approach is a significant differentiator. For raw image generation quality and artistic output, Midjourney is still preferred by many creatives. Canva AI serves a similar but less technically sophisticated audience using Firefly in a simplified context.</p>`
    },

    'copy-ai': {
        long_description: `<p>Copy.ai is an AI writing platform focused on marketing and sales content generation. It provides a range of tools for generating ad copy, sales emails, product descriptions, blog posts, and social media content using large language models.</p><p>Founded in 2020, Copy.ai was one of the early entrants to the AI copywriting tool market. It has since expanded beyond single-output generation toward multi-step workflow automation for marketing teams, introducing a workflow builder for automated content pipelines.</p><p>Copy.ai competes primarily with Jasper AI in the marketing-focused writing tool space, though both also compete with general-purpose AI assistants like ChatGPT as those tools have improved at marketing-related tasks.</p>`,
        how_it_works: `<p>Users select from a library of content types — ad copy, product descriptions, email subject lines, blog intros — enter relevant context such as product name and audience, and generate multiple output options simultaneously. The Chat interface allows conversational content generation similar to ChatGPT. Workflows allow users to chain generation steps into automated content pipelines that process inputs and produce structured outputs at scale. Team features allow shared access to brand voices and content templates.</p>`,
        workflows: [
            { title: 'Sales Email Sequence Generation', description: 'Sales teams use Copy.ai to generate multi-step cold email sequences, producing initial contact messages, follow-ups, and closing prompts from prospect information inputs.' },
            { title: 'Ad Copy Variant Testing', description: 'Marketing teams generate multiple ad headline and body variants for A/B testing across platforms, rapidly expanding the pool of creative options without proportional writing time.' },
            { title: 'Product Description Scaling', description: 'E-commerce teams automate product description generation using Copy.ai workflows, processing product attributes in bulk to produce formatted descriptions at scale.' },
            { title: 'Blog Content Outlines and Drafts', description: 'Content marketers use Copy.ai to generate content outlines and first draft sections from keyword briefs, reducing time-to-draft for regular publishing schedules.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Marketing copy templates (90+ types)', 'AI chat interface for conversational generation', 'Brand voice configuration', 'Multi-language support', 'Team project collaboration'] },
            { group: 'Advanced Capabilities', items: ['Workflow builder for automated content pipelines', 'CRM and data source integrations', 'Bulk generation via workflows', 'Infobase for brand and product knowledge', 'API access'] }
        ],
        best_for: ['Marketing teams producing regular content at scale', 'Sales development representatives writing outreach sequences', 'E-commerce businesses with large product catalogues', 'Digital agencies managing copy for multiple clients', 'Content marketers working to publishing schedules'],
        pros: ['Broad template library for common marketing formats', 'Workflow automation for bulk content generation', 'Team collaboration built in', 'Can generate multiple variants simultaneously', 'Competitive pricing relative to Jasper'],
        cons: ['Output quality requires editing and is not publish-ready', 'Less suitable for deep editorial or technical content', 'Workflow builder has a learning curve', 'Less strong on SEO-specific features than Jasper+Surfer', 'General-purpose AI tools increasingly cover similar use cases'],
        pricing_overview: `<p>Copy.ai offers a free plan with limited monthly word generation. Paid plans include unlimited generation, access to workflows, more team seats, and priority support. Enterprise plans offer custom pricing, dedicated support, and integration capability. Pricing is structured per workspace with a seat-based expansion model.</p>`,
        comparison_summary: `<p>Copy.ai's closest competitor is Jasper AI, which targets a similar marketing audience. Jasper tends to position itself more at enterprise clients with a higher price point and brand voice sophistication. Copy.ai competes on accessibility and workflow automation. Both compete with general-purpose assistants like ChatGPT, which increasingly handle marketing copy tasks without a dedicated subscription.</p>`
    },

    'zapier-ai': {
        long_description: `<p>Zapier is an automation platform that connects web applications and automates repetitive workflows between them without requiring code. Zapier AI refers to the AI-powered features within Zapier, including an AI chatbot builder, AI-powered workflow suggestions, and integrations with AI services like ChatGPT and Claude within automation workflows.</p><p>Zapier has integrated AI in two primary ways: it uses AI to help users describe and build automations in natural language, and it provides pre-built integrations with AI tools that users can incorporate into their workflows, such as sending data to ChatGPT and receiving processed output.</p><p>Zapier is widely used by small businesses, marketing teams, and operations professionals who need to connect disparate tools without engineering resources.</p>`,
        how_it_works: `<p>Users create "Zaps" — automated workflows with a trigger and one or more actions. With AI features, users can describe a desired workflow in natural language and Zapier will suggest or build the automation structure. AI steps within Zaps allow users to send data to ChatGPT or another AI model, receive AI-processed output, and continue the automation chain. The AI Chatbot feature allows users to deploy a trained conversational assistant on their own website using their content.</p>`,
        workflows: [
            { title: 'Lead Routing with AI Classification', description: 'Sales teams build Zaps that receive form submissions, send them to an AI model for lead quality scoring, and route high-score leads to CRM with priority tags.' },
            { title: 'AI-Powered Content Distribution', description: 'Marketing teams create Zaps that trigger when a new blog post is published, send the content to ChatGPT for social media adaptation, and post the result to social platforms automatically.' },
            { title: 'Customer Support Triage', description: 'Support teams use Zapier to capture incoming tickets, categorise them using an AI step, and route to the appropriate team or auto-respond with relevant information.' },
            { title: 'Data Enrichment Pipelines', description: 'Operations teams pull contact data from a CRM, pass it through an AI step for enrichment or summarisation, and write the result back into the CRM or a spreadsheet.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['No-code workflow automation between 6,000+ apps', 'Trigger and action-based Zap builder', 'AI-assisted workflow creation from description', 'Filter, delay, and conditional logic steps', 'Multi-step workflow support'] },
            { group: 'AI-Specific Features', items: ['AI step for ChatGPT and other model integration', 'Zapier AI Chatbot builder', 'Natural language Zap building', 'AI-powered workflow recommendations', 'AI data formatting and transformation steps'] }
        ],
        best_for: ['Small businesses and operations teams automating repetitive tasks', 'Marketing teams connecting their tool stack', 'Non-technical users needing workflow automation without code', 'Sales operations teams enriching and routing leads', 'Support teams automating ticket triage'],
        pros: ['Largest app integration library of any automation platform', 'No-code approach accessible to non-technical users', 'AI integration makes AI tools accessible within existing workflows', 'Large template library for common automation patterns', 'Reliable and well-established platform'],
        cons: ['Complex multi-step workflows can become expensive at scale', 'AI step quality depends on prompt design quality', 'Not suitable for highly complex logic (better served by Make or n8n)', 'Free tier has limited task volume', 'Debugging failed Zaps requires familiarity with the platform'],
        pricing_overview: `<p>Zapier offers a free tier with a limited number of tasks per month and single-step Zaps only. Paid plans increase the monthly task volume, unlock multi-step Zaps, filtering, and premium app integrations. AI-specific features such as the Chatbot builder require paid plans. Pricing scales with task volume and number of premium features used.</p>`,
        comparison_summary: `<p>Zapier's primary competitors are Make (formerly Integromat) and n8n. Make offers more advanced workflow logic at a lower price per operation, preferred by technical users. n8n is open-source and self-hostable, targeting developers. Zapier's advantage is its app library breadth and ease of use for non-technical users. For AI-heavy automation pipelines, specialist tools or custom code integrations may outperform a Zapier-based approach.</p>`
    },

    'murf-ai': {
        long_description: `<p>Murf AI is an AI voice generation and text-to-speech studio platform designed for content creators, educators, and marketing teams. It allows users to generate studio-quality voiceovers from text using a library of AI voices across multiple accents and languages.</p><p>Unlike ElevenLabs which targets high-fidelity voice cloning and API developers, Murf is positioned as a complete studio tool for producing voiceover content — with a script editor, timeline, media sync, and background music features built into the interface.</p><p>It is primarily used for producing e-learning course narration, marketing video voiceovers, presentation narration, and podcast-style content without professional recording equipment or voice talent.</p>`,
        how_it_works: `<p>Users type or paste a script into the Murf studio editor, select a voice from the library, and adjust speaking speed, pitch, and emphasis. The platform generates audio which can be previewed and modified at the sentence level before exporting. Users can add background music, sync narration with video or slides, and adjust timing on a timeline. The resulting audio or video can be exported in standard formats. Team workspaces allow collaborative project access.</p>`,
        workflows: [
            { title: 'E-Learning Narration Production', description: 'Instructional designers write course scripts, generate narration in Murf using a consistent AI voice, and sync the audio with slide decks or screen recordings.' },
            { title: 'Marketing Video Voiceover', description: 'Marketing teams produce explainer video narrations from scripts without booking voice talent or recording studios, reducing production turnaround.' },
            { title: 'Localised Content in Multiple Languages', description: 'Content teams produce the same narrated content in multiple languages by adjusting the script and selecting a corresponding language voice in Murf.' },
            { title: 'Podcast Show Notes and Script Rendering', description: 'Podcasters convert written scripts into narrated audio segments for solo episodes or audio articles without recording setups.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['120+ AI voices across 20+ languages', 'Pitch, speed, and emphasis controls', 'Script editor with sentence-level voice adjustment', 'Audio export in multiple formats', 'Background music library'] },
            { group: 'Advanced Capabilities', items: ['Voice cloning (on select plans)', 'Video and slide sync timeline', 'Team workspace collaboration', 'API access for developers', 'Commercial usage rights on paid plans'] }
        ],
        best_for: ['E-learning and instructional design teams', 'Marketing teams producing video content', 'Businesses localising content into multiple languages', 'YouTubers and video creators adding narration', 'Podcast producers creating audio articles'],
        pros: ['Clean studio interface designed for non-technical users', 'Broad voice library with realistic output', 'Timeline and media sync for video production', 'Clear commercial usage rights on paid plans', 'Strong language and accent coverage'],
        cons: ['Voice naturalness is below ElevenLabs for demanding use cases', 'Voice cloning requires a higher tier plan', 'Credit limits on lower plans may constrain high-volume use', 'Less developer-oriented than ElevenLabs', 'Free tier is limited for professional output'],
        pricing_overview: `<p>Murf AI offers a free plan with limited voice access and audio minutes. Paid plans increase the monthly audio generation allowance, unlock commercial usage, expand voice options, and add features such as voice cloning and video sync. Team plans allow shared project access with multiple editors. All paid plans are available on monthly or annual billing.</p>`,
        comparison_summary: `<p>Murf AI is most directly compared to ElevenLabs and Descript Overdub. ElevenLabs produces more natural voice output and is better suited for developer integration and high-fidelity cloning. Descript Overdub is specifically focused on correcting recorded audio. Murf differentiates on its complete studio production environment — script editing, timeline, music, and export — making it more suitable for teams producing finished content rather than technical integrations.</p>`
    },

    'quillbot': {
        long_description: `<p>QuillBot is an AI writing assistant tool specialising in paraphrasing, grammar correction, summarisation, and citation generation. It is widely used by students, academics, and professional writers as a writing improvement and rewriting tool rather than a full content generator.</p><p>The core paraphrasing engine allows users to rephrase text while preserving meaning — useful for improving readability, reducing repetition, or adapting a writing style. QuillBot has expanded to include a full suite of writing tools: a grammar checker, summariser, plagiarism checker, citation generator, and a translator.</p><p>It is available as a browser extension integrating with Google Docs and Microsoft Word, as well as a standalone web application, making it accessible across common writing environments.</p>`,
        how_it_works: `<p>Users paste text into the QuillBot paraphraser, select a paraphrasing mode (Standard, Fluency, Formal, Simple, Creative, Expand, or Shorten), and generate a rewritten version. Synonyms are highlighted and can be changed individually. The summariser condenses longer texts to key points. The grammar checker identifies and corrects errors inline. The citation generator produces formatted academic references from URLs, DOIs, or book details. All tools are accessible within the QuillBot web interface or extension.</p>`,
        workflows: [
            { title: 'Academic Paraphrasing for Papers', description: 'Students use QuillBot to rephrase source material and integrate it into their own writing, avoiding direct copying while maintaining academic integrity.' },
            { title: 'Document Simplification', description: 'Professionals use QuillBot\'s "Simplify" mode to convert complex or technical language into plain English for general audiences.' },
            { title: 'Grammar and Style Cleanup', description: 'Writers run drafts through QuillBot\'s grammar checker to identify and correct errors before submission or publication.' },
            { title: 'Source Summarisation', description: 'Researchers use the summariser to condense long articles, reports, and papers to key points as part of a literature review process.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Paraphrasing with 7 mode options', 'Grammar checker', 'Summariser', 'Citation generator (APA, MLA, Chicago)', 'Translator'] },
            { group: 'Advanced Capabilities', items: ['Plagiarism checker (Premium)', 'Full document paraphrasing', 'Synonym adjustment per word', 'Google Docs and Word extension', 'Faster processing (Premium)'] }
        ],
        best_for: ['Students writing academic papers', 'ESL writers improving English fluency', 'Researchers citing and summarising sources', 'Content writers repurposing existing material', 'Professionals adapting technical writing for different audiences'],
        pros: ['Effective paraphrasing with multiple style modes', 'Broad writing tool suite in one product', 'Browser extension works within Google Docs and Word', 'Citation generator covers major academic formats', 'Accessible pricing with a usable free tier'],
        cons: ['Paraphrasing can alter intended meaning if not reviewed', 'Not a content generator — requires source text to work from', 'Plagiarism checker requires Premium', 'Extension features vary between browsers', 'Less suitable for long-form original content generation'],
        pricing_overview: `<p>QuillBot offers a free plan with access to limited paraphrasing modes, a word limit per session, and basic grammar checking. QuillBot Premium removes word limits, unlocks all paraphrasing modes, enables full-document processing, and includes the plagiarism checker. Annual billing provides a discounted rate versus monthly.</p>`,
        comparison_summary: `<p>QuillBot's primary competitors are Wordtune and Grammarly in the rewriting and editing space. Wordtune focuses specifically on sentence rewrites and tone adjustment. Grammarly emphasises grammar correction and style improvements. QuillBot differentiates on its paraphrasing depth and academic tool suite (citation generator, summariser). For full content generation rather than rewriting, tools like Jasper or ChatGPT are more appropriate.</p>`
    },

    'luma-ai': {
        long_description: `<p>Luma AI is an AI video and 3D content generation platform. It offers Dream Machine, a text-to-video and image-to-video generation model, and also provides tools for capturing 3D scenes from photographs using neural radiance fields (NeRF) technology. Luma was founded in 2021 and focuses on AI-generated visual media for creative and commercial applications.</p><p>Dream Machine gained significant attention in 2024 for producing high-quality, physically realistic video from text prompts and reference images. The platform positions itself as a professional-grade creative tool for filmmakers, designers, and visual content producers.</p><p>Luma AI targets creative professionals seeking high physical coherence in AI-generated video — a known limitation of other video generation tools — along with product teams needing 3D capture without specialist hardware.</p>`,
        how_it_works: `<p>For Dream Machine video generation, users enter a text prompt and optionally provide a reference image as the first frame. The model generates a short video clip (typically 5–10 seconds) with motion and physical coherence. Multiple clips can be generated from the same prompt and stitched together. For 3D capture, users upload a series of photographs taken around an object or space, and Luma AI processes them into a navigable 3D model. Both outputs can be downloaded or shared.</p>`,
        workflows: [
            { title: 'Video Concept Visualization', description: 'Directors and art directors convert written scene descriptions into video clips for use as visual references in production planning and client presentations.' },
            { title: 'Product 3D Model Capture', description: 'E-commerce and product teams photograph physical objects from multiple angles, then use Luma AI to generate interactive 3D models for web embedding.' },
            { title: 'Animated Social Media Content', description: 'Content creators generate short animated clips from still images or prompts for use as engaging social media posts without live filming.' },
            { title: 'Scene Concept Generation', description: 'Game designers and set designers generate environmental and atmospheric video references as early-stage visual exploration tools.' }
        ],
        feature_groups: [
            { group: 'Dream Machine (Video)', items: ['Text-to-video generation', 'Image-to-video generation', 'Physically coherent motion', 'Clip extension', 'Multiple output resolution options'] },
            { group: '3D Capture', items: ['Photo-based 3D scene capture', 'NeRF-based model generation', '3D model download and embed', 'Web-embeddable interactive 3D viewer', 'API for developer integration'] }
        ],
        best_for: ['Filmmakers and visual directors creating concept content', 'Product and e-commerce teams needing 3D models', 'Social media creators producing dynamic visual content', 'Game designers exploring environment references', 'Developers building 3D capture into applications'],
        pros: ['Strong physical coherence in video generation', 'Unique combined offering of video and 3D capture', 'Image-to-video capability for precise starting frame control', 'API access for programmatic video generation', 'Improving quality with each model update'],
        cons: ['Video clip duration is limited (seconds per generation)', 'Credit costs can increase rapidly at production volumes', 'Output consistency varies with prompt complexity', '3D capture quality depends on photograph quality and coverage', 'Less widespread adoption ecosystem than Runway'],
        pricing_overview: `<p>Luma AI offers a free tier with a limited monthly generation credit allocation. Paid plans increase monthly credits and provide access to higher resolution outputs and priority generation. API access is available for developers with usage-based pricing. Enterprise agreements for high-volume commercial use are available.</p>`,
        comparison_summary: `<p>Luma AI Dream Machine competes most directly with Runway Gen-3, Pika, and Sora (when available). Runway is more established with a broader toolkit for professional video workflows. Pika is simpler and well-suited for casual creators. Luma differentiates on physical realism and its unique combination of video generation with 3D scene capture. Sora (OpenAI) remains the aspirational benchmark but has limited public availability.</p>`
    },

    'writesonic': {
        long_description: `<p>Writesonic is an AI writing and content generation platform targeting marketing teams, content creators, and SEO-focused writers. It provides tools for generating blog posts, landing pages, ad copy, product descriptions, and social media content across a large template library.</p><p>Founded in 2020, Writesonic has expanded to include a conversational AI assistant (Chatsonic, built on ChatGPT with real-time web access), an AI article writer, and SEO-oriented content tools. It positions itself as a more SEO-aware alternative to general-purpose writing tools, with features like keyword input integration and Google Search Console connection.</p><p>Writesonic competes with Jasper and Copy.ai in the marketing AI writing space, with a stronger emphasis on accessibility and a lower entry price point.</p>`,
        how_it_works: `<p>Users select a content type from Writesonic's template library, provide context such as product name, keywords, and audience, and generate output in multiple draft variations. Chatsonic allows conversational interaction including web search for current information. The long-form article writer takes a topic or keyword, generates an outline, and produces a full draft that users can edit within Writesonic's document editor. SEO integrations allow keyword targeting to be applied during generation.</p>`,
        workflows: [
            { title: 'SEO Blog Article Generation', description: 'Content teams input target keywords, receive an AI-generated outline, then produce a full blog post draft using Writesonic\'s long-form writer, reducing time from keyword to draft.' },
            { title: 'Landing Page Copy Creation', description: 'Marketing teams generate headline, subheading, and body copy variants for landing pages from a product or offer description.' },
            { title: 'Real-Time Web Content with Chatsonic', description: 'Users interact with Chatsonic for current event research and content that requires up-to-date information, combining generation with real-time search.' },
            { title: 'Social Media Caption Generation', description: 'Social media managers generate platform-specific post captions, hashtag sets, and ad copy from campaign briefs or product information.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['100+ content templates', 'Long-form article writer', 'Chatsonic (AI assistant with web access)', 'Ad copy and landing page generator', 'Multilingual content generation'] },
            { group: 'Advanced Capabilities', items: ['SEO keyword integration', 'Google Search Console integration', 'Brand Voice configuration', 'API access', 'Bulk generation'] }
        ],
        best_for: ['SEO and content marketing teams', 'Bloggers and content publishers', 'Small business owners managing their own marketing', 'Social media managers', 'Marketing agencies producing content for multiple clients'],
        pros: ['Competitive pricing relative to Jasper', 'Chatsonic provides real-time web access for current content', 'Large template library for common marketing formats', 'SEO-aware content generation features', 'Multi-language support'],
        cons: ['Output quality requires editing before publication', 'Less established than Jasper for enterprise marketing teams', 'Template proliferation can make tool navigation complex', 'Brand Voice training is less refined than competitor tools', 'General-purpose AI tools increasingly overlap capabilities'],
        pricing_overview: `<p>Writesonic offers a free plan with limited monthly word generation. Paid plans are priced per user on a monthly or annual basis, with higher word limits and access to all templates and advanced features. Business plans support team access and higher volumes. Pricing is generally positioned below Jasper, making it more accessible for individual creators and small teams.</p>`,
        comparison_summary: `<p>Writesonic most directly competes with Copy.ai and Jasper AI. Jasper is considered more enterprise-grade with stronger brand voice controls. Copy.ai has a strong workflow automation capability. Writesonic differentiates on price and its Chatsonic feature offering real-time web access for content generation. For pure content quality and agency use, ChatGPT or Claude with custom prompting is increasingly competitive without a dedicated subscription.</p>`
    },

    'notion': {
        long_description: `<p>Notion is a connected workspace platform that combines note-taking, project management, databases, wikis, and documentation into a single flexible tool. Founded in 2013, it has become a widely used productivity application for individuals, startups, and enterprise teams to organise information and manage work across contexts.</p><p>Notion's core concept is the "block" — every element of a page (text, images, tables, databases, code blocks) is a modular block that can be rearranged, nested, and linked. This flexibility allows users to build custom workspaces that serve as documentation systems, task managers, knowledge bases, and planning tools simultaneously.</p><p>This is the core Notion product (distinct from Notion AI, the AI add-on feature layer). See the Notion AI page for details on AI-specific capabilities.</p>`,
        how_it_works: `<p>Users create pages within a workspace, adding blocks of different types to structure content. Tables and databases allow structured data to be queried and filtered with different views (table, board, calendar, gallery). Relations link databases together. Pages can be shared publicly or with specific team members. Templates provide starting structures for common use cases. The sidebar organises the workspace hierarchy, and a global search allows finding any content across the workspace.</p>`,
        workflows: [
            { title: 'Team Wiki and Knowledge Base', description: 'Teams build internal wikis in Notion documenting processes, onboarding guides, and product knowledge in a structured, searchable format accessible to all team members.' },
            { title: 'Project and Task Tracking', description: 'Project teams maintain task databases with status, owner, and deadline fields, filtered into personal and team views for workload visibility.' },
            { title: 'CRM and Database Management', description: 'Small teams use Notion databases as lightweight CRM systems, tracking contacts, deals, and communication history without a dedicated CRM tool.' },
            { title: 'Content Calendar Planning', description: 'Content and marketing teams manage editorial calendars in Notion, tracking article topics, status, and publication dates in a linked database.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Flexible block-based page editor', 'Relational databases with multiple views', 'Real-time collaboration', 'Page sharing and published web pages', 'Template library'] },
            { group: 'Advanced Capabilities', items: ['Notion AI add-on (separate subscription)', 'API for integrations', 'Automations', 'Enterprise SSO and admin controls', 'Advanced permission management'] }
        ],
        best_for: ['Startups and small teams needing an all-in-one workspace', 'Individuals managing personal knowledge and projects', 'Teams building internal wikis and documentation', 'Content and marketing teams managing editorial workflows', 'Operations teams building custom databases and workflows'],
        pros: ['Extremely flexible and customisable to many use cases', 'Single platform replacing multiple specialist tools', 'Strong template ecosystem', 'Good collaboration features on team plans', 'Continuously updated with new features'],
        cons: ['Can be overly complex for simple use cases', 'Performance can degrade with very large workspaces', 'Offline access is limited', 'Steep learning curve for database and relation features', 'Advanced features require paid plans'],
        pricing_overview: `<p>Notion offers a free plan for individuals with unlimited pages and blocks with limited collaboration features. Plus and Business plans add unlimited team members, more admin controls, and features like unlimited automation. Enterprise adds SSO, audit logs, and dedicated support. Notion AI is an additional per-member per-month add-on across all plans.</p>`,
        comparison_summary: `<p>Notion's primary competitors are Confluence (Atlassian), Coda, and ClickUp in the productivity workspace space. Confluence is more established in enterprise engineering environments with Jira integration. Coda is more formula-driven and powerful for complex database logic. ClickUp is more task and project management focused. Notion differentiates on its page flexibility and the breadth of use cases its block structure supports.</p>`
    }

};

let patched = 0;
const modified = [];
for (const tool of tools) {
    if (enrichment[tool.id]) {
        Object.assign(tool, enrichment[tool.id]);
        patched++;
        modified.push(tool.id);
    }
}
writeFileSync(PATH, JSON.stringify(tools, null, 2));
console.log(`Batch 3 complete. Patched ${patched} tools: ${modified.join(', ')}`);
