// Phase 8.6 — Enrichment Batch 5 (tools 41–50)
import { readFileSync, writeFileSync } from 'fs';
const PATH = './data/tools.json';
const tools = JSON.parse(readFileSync(PATH, 'utf8'));

const enrichment = {

    'intercom-fin': {
        long_description: `<p>Intercom Fin is an AI customer support agent developed by Intercom, designed to automatically resolve customer support queries without human involvement. It is built on large language models and trained to understand a company's support documentation to provide accurate, contextual responses to customer questions.</p><p>Fin operates within Intercom's existing customer messaging platform, meaning it can be deployed by teams already using Intercom without adopting a separate tool. It handles incoming conversations autonomously and escalates to human agents when queries fall outside its ability to resolve confidently.</p><p>Intercom Fin targets businesses running customer support operations at scale, where a reduction in repetitive query volume for human agents has direct cost and efficiency implications.</p>`,
        how_it_works: `<p>Fin is connected to a company's help centre articles and support documentation. When a customer sends a support message, Fin attempts to resolve it by referencing the trained content base and providing a direct answer. If it cannot confidently resolve the query, it routes the conversation to a human agent. Usage and resolution rate data is tracked in Intercom's reporting dashboard. Fin can be configured with custom personas, escalation rules, and coverage windows.</p>`,
        workflows: [
            { title: 'First-Contact Resolution for Common Queries', description: 'Support teams deploy Fin to handle frequently asked questions, account queries, and documentation-based support requests without human agent involvement.' },
            { title: 'After-Hours Support Coverage', description: 'Businesses use Fin to provide 24/7 support coverage during hours when human agents are unavailable, resolving straightforward queries around the clock.' },
            { title: 'Ticket Volume Reduction', description: 'Support operations use Fin to reduce the volume of incoming tickets that reach human agents, allowing teams to focus on complex or high-value customer issues.' },
            { title: 'Multilingual Support Expansion', description: 'Businesses use Fin to handle support queries in multiple languages without proportionally scaling multilingual agent headcount.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['AI-powered autonomous query resolution', 'Help centre and documentation training', 'Human agent handoff on low-confidence queries', 'Conversation history context', 'Multiple channel support'] },
            { group: 'Advanced Capabilities', items: ['Custom AI persona configuration', 'Resolution rate and performance analytics', 'Escalation logic configuration', 'Multilingual response support', 'Integration with Intercom workflows'] }
        ],
        best_for: ['Customer support teams with high repetitive query volume', 'SaaS companies with extensive help documentation', 'E-commerce businesses managing order and account queries', 'Teams requiring 24/7 support coverage without full staffing', 'Intercom platform users already invested in the ecosystem'],
        pros: ['Natively integrated into the Intercom platform', 'Can resolve common queries without human involvement', 'Resolution rate data provides clear ROI measurement', 'Configurable escalation logic', 'Multilingual capability without translation overhead'],
        cons: ['Effectiveness depends heavily on the quality of connected documentation', 'Requires existing Intercom subscription', 'Fin usage is priced per resolution, adding cost at scale', 'Cannot handle complex or emotional support situations well', 'Initial setup and documentation quality investment required'],
        pricing_overview: `<p>Intercom Fin is available as part of Intercom's plans, typically with pricing based on the number of resolutions Fin completes. Intercom's base pricing requires a platform subscription, on top of which Fin usage is charged per resolved conversation. Enterprise plans may offer different pricing structures. Total cost depends on query volume and resolution rate.</p>`,
        comparison_summary: `<p>Fin competes with Zendesk AI, Freshdesk AI, and Tidio in the AI customer support category. Zendesk AI is the most direct enterprise competitor with a similar resolution-focused model. Freshdesk offers AI features at a lower price point. Tidio targets smaller businesses with a simpler chatbot tool. Fin's advantage is its integration depth within the Intercom platform and the quality of its LLM-based responses for documentation-grounded queries.</p>`
    },

    'zendesk-ai': {
        long_description: `<p>Zendesk AI is the suite of artificial intelligence features embedded in Zendesk, one of the most widely used enterprise customer support platforms. These features include AI-powered ticket triage and classification, automated responses via AI agents, and intelligent suggestions for human agents handling live conversations.</p><p>Zendesk AI is designed for support operations teams managing large volumes of customer interactions across email, chat, and social channels. Rather than being a standalone AI product, it is an enhancement layer across the Zendesk product suite, making it most relevant for existing Zendesk customers.</p><p>Zendesk AI competes primarily with Intercom Fin and Freshdesk AI in the enterprise support platform space, where AI-assisted efficiency is measured through metrics like first contact resolution, handle time, and deflection rate.</p>`,
        how_it_works: `<p>AI features activate within the existing Zendesk interface. Ticket triage automatically categorises incoming tickets by intent and routes them to appropriate teams or queues. AI agents (bots) handle tier-0 queries by surfacing relevant knowledge base content or resolving common requests autonomously. For human agents, AI provides suggested responses, summarises ticket history, and highlights key sentiment in customer messages. Administrators configure triage rules, bot behaviour, and escalation paths in the Zendesk admin interface.</p>`,
        workflows: [
            { title: 'Automated Ticket Routing and Classification', description: 'Support teams configure Zendesk AI to classify incoming tickets by topic and intent, routing them to specialist queues automatically without manual triage.' },
            { title: 'Bot-Handled Tier-0 Query Resolution', description: 'AI agents handle simple queries — password resets, order status, FAQ responses — by connecting to knowledge base articles and completing resolutions without human handoff.' },
            { title: 'Agent Productivity with AI Suggestions', description: 'Live agents use AI-suggested response drafts and ticket summaries to handle conversations faster, maintaining quality with reduced cognitive load.' },
            { title: 'CSAT Prediction and Escalation', description: 'Zendesk AI analyses sentiment and ticket signals to predict customer satisfaction risk and flag high-priority cases for senior agent escalation.' }
        ],
        feature_groups: [
            { group: 'Core AI Features', items: ['AI-powered ticket triage and classification', 'Automated intent detection', 'AI agent (bot) for tier-0 resolution', 'Knowledge base suggestion integration', 'Agent response suggestions'] },
            { group: 'Advanced Capabilities', items: ['Conversation summarisation', 'CSAT prediction and sentiment analysis', 'Intelligent workflow automation', 'Omnichannel AI across email, chat, social', 'Reporting on AI performance and deflection'] }
        ],
        best_for: ['Enterprise support teams already on Zendesk', 'Operations managers seeking measurable deflection and efficiency gains', 'High-volume support centres with repetitive query types', 'Multi-channel customer support organisations', 'Teams tracking CSAT and first-contact resolution metrics'],
        pros: ['Deep integration with the established Zendesk platform', 'Broad AI feature coverage across triage, bots, and agent assist', 'Enterprise-grade security and compliance', 'Measurable deflection and efficiency metrics', 'No separate tooling required for Zendesk users'],
        cons: ['AI features require higher-tier Zendesk plans', 'Bot capabilities depend on knowledge base quality', 'Initial configuration requires time and support expertise', 'AI agent limitations apply for complex or emotional queries', 'Vendor lock-in with Zendesk platform dependency'],
        pricing_overview: `<p>Zendesk AI features are available across Zendesk Suite plans, with access to different tiers of AI capability depending on the plan level. Advanced AI features — including more sophisticated bots, CSAT prediction, and agent assistance — are part of higher-tier plans. AI agent usage may be billed separately based on resolution volume. Enterprise plans allow custom configuration and pricing.</p>`,
        comparison_summary: `<p>Zendesk AI and Intercom Fin are the primary enterprise AI support platforms. Zendesk has more comprehensive omnichannel coverage and a longer enterprise track record. Intercom Fin is newer but noted for its LLM quality and clean resolution reporting. Freshdesk AI targets mid-market with a lower price point. For less complex support needs, Tidio and similar chatbot-first tools are more accessible alternatives.</p>`
    },

    'v0-by-vercel': {
        long_description: `<p>v0 is an AI-powered UI generation tool developed by Vercel, the cloud platform widely used for frontend and Next.js deployments. It generates React component code from natural language descriptions, producing functional, styled UI code that developers can copy directly into their projects.</p><p>v0 uses a multi-model AI approach to generate shadcn/ui and Tailwind CSS based components that are production-ready starting points. It significantly reduces the time required to scaffold UI components, from hours of manual coding to seconds of AI generation.</p><p>v0 is targeted at frontend developers and full-stack engineers who work within the React and Next.js ecosystem. It is particularly useful for rapid prototyping, building admin interfaces, and component scaffolding.</p>`,
        how_it_works: `<p>Users describe the UI component or page layout they want in natural language — for example, "a pricing table with three tiers" — and v0 generates a complete React component using shadcn/ui, Tailwind CSS, and TypeScript. The generated code is displayed with a live preview and can be copied, refined through follow-up prompts, or forked and edited within the v0 interface. The generated code is designed to be pasted directly into a Next.js project with minimal modification.</p>`,
        workflows: [
            { title: 'Component Scaffolding', description: 'Developers use v0 to generate boilerplate for common components — forms, tables, dashboards, navigation — and then customise them in their local project.' },
            { title: 'Rapid UI Prototyping', description: 'Product teams describe desired interfaces and generate working React mockups in minutes for stakeholder review and iteration feedback.' },
            { title: 'Admin Interface Generation', description: 'Full-stack developers use v0 to quickly generate data tables, CRUD interfaces, and settings pages for internal tools without building from scratch.' },
            { title: 'Component Iteration via Follow-Up Prompts', description: 'Developers iterate on generated components by describing changes — "make the button larger, add a hover state" — and v0 updates the code accordingly.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Text-to-React component generation', 'shadcn/ui and Tailwind CSS output', 'TypeScript support', 'Live preview of generated UI', 'Code copy with one click'] },
            { group: 'Advanced Capabilities', items: ['Multi-turn refinement via prompt iteration', 'Vercel deployment integration', 'Image-to-component generation', 'Next.js ecosystem compatibility', 'Fork and continue in browser editor'] }
        ],
        best_for: ['Frontend developers in the React and Next.js ecosystem', 'Full-stack developers building internal tools', 'Startups prototyping UI quickly', 'Developers who use shadcn/ui and Tailwind CSS', 'Engineers scaffolding admin and dashboard interfaces'],
        pros: ['Dramatically reduces component scaffolding time', 'Output is production-quality React with established libraries', 'Lives preview and easy code copy', 'Multi-turn iteration improves specificity', 'Deep integration with Vercel deployment workflow'],
        cons: ['Output is specifically for React with shadcn/ui — not framework-agnostic', 'Generated code still requires developer review and integration', 'Complex custom design systems may require significant adaptation', 'Free tier has generation limits', 'Vercel ecosystem lock creates a dependency for the full pipeline'],
        pricing_overview: `<p>v0 is available via a free tier with limited monthly generation credits. Paid plans offer more monthly credits and potentially higher quality generation options. As a Vercel product, it may be bundled with or discounted for Vercel Pro and Team plans. Pricing follows Vercel's credit-based model.</p>`,
        comparison_summary: `<p>v0 competes in the AI code generation and UI scaffolding space with GitHub Copilot, Cursor, and tools like Bolt and Lovable. Copilot and Cursor generate code within the developer's editor. Bolt and Lovable target full-application generation from prompts. v0's differentiation is its focus specifically on React/Next.js UI components with shadcn and Tailwind output — narrower than full-app generators but higher quality within that stack.</p>`
    },

    'framer': {
        long_description: `<p>Framer is a visual website builder that combines no-code design flexibility with a high-quality publishing engine optimised for performance. It allows designers and marketers to create websites without writing code, while also supporting custom React component integration for developers who want to extend the platform.</p><p>Framer AI is the AI-enhanced layer that allows users to generate website sections, landing pages, and copy from text prompts directly within the Framer editor. The AI generates styled, responsive content that integrates immediately with the existing design canvas.</p><p>Framer targets design-led teams, landing page builders, and marketing departments that want significant visual control without a full engineering team. It competes primarily with Webflow and Squarespace in the no-code website builder market.</p>`,
        how_it_works: `<p>Users design pages in Framer's visual canvas using a component and frame-based system. Framer AI allows users to type a prompt describing a section (e.g., "pricing table with three columns") and the AI inserts a styled, responsive section into the design. Copy can also be generated from prompts. The designer can edit all generated content using the standard visual editor. Sites are published directly from Framer with automatic performance optimisation and CDN hosting.</p>`,
        workflows: [
            { title: 'AI-Assisted Landing Page Generation', description: 'Marketing teams describe the landing page concept in Framer AI and receive a visually styled page skeleton with copy and layout, ready for refinement.' },
            { title: 'Section and Component Generation', description: 'Designers use Framer AI to insert specific sections (hero, testimonials, pricing, FAQ) with appropriate layout and placeholder copy automatically.' },
            { title: 'Design and Publish Without Code', description: 'Marketing teams build, iterate, and publish marketing pages without engineering dependency, using Framer\'s visual editor and hosting in a single workflow.' },
            { title: 'React Component Integration for Advanced Teams', description: 'Developers integrate custom React components into Framer pages for complex interactions that the no-code tools cannot handle natively.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Visual no-code website editor', 'Responsive design system', 'Animation and interaction builder', 'Framer CMS for content management', 'One-click publishing with CDN hosting'] },
            { group: 'AI Capabilities', items: ['AI section generation from text prompt', 'AI copy generation', 'AI-powered layout suggestions', 'Responsive output from AI prompt', 'Integrated with standard editor workflow'] }
        ],
        best_for: ['Marketing teams building landing pages without engineering', 'Designers producing portfolio and promotional sites', 'Startups shipping marketing pages rapidly', 'Agencies building client websites visually', 'Design-led teams wanting visual control over web output'],
        pros: ['High visual quality output without code', 'Fast publishing and CDN performance built in', 'AI section generation reduces design time significantly', 'CMS for content-managed pages', 'React integration for developers needing custom functionality'],
        cons: ['Can be more complex than simple website builders for non-designers', 'Team plans required for multi-seat collaboration', 'CMS is less mature than dedicated CMS platforms', 'AI output requires design refinement to match brand precisely', 'Exporting code for self-hosting is limited'],
        pricing_overview: `<p>Framer offers a free plan for single projects with Framer subdomain hosting. Paid site plans add custom domains, more CMS items, and removed Framer branding at a per-site monthly price. Workspace plans cover team collaboration with shared project access. AI features are included within site and workspace plans.</p>`,
        comparison_summary: `<p>Framer competes most directly with Webflow in the no-code web design space. Webflow offers more advanced CMS and e-commerce capability, while Framer is preferred for high-quality motion design and visual polish. Squarespace and Wix target less design-sophisticated users. For AI-first site generation, Durable and Hostinger AI Builder are simpler but less capable design tools. Framer differentiates on design quality and animation capability within the no-code category.</p>`
    },

    'webflow': {
        long_description: `<p>Webflow is a professional no-code web design and CMS platform that allows designers to build visually complex, responsive websites without writing frontend code. It generates clean, production-ready HTML, CSS, and JavaScript from its visual editor, and includes a built-in CMS for content-managed sites.</p><p>Webflow is used primarily by designers, agencies, and marketing teams who require full visual control over website design and do not want to be constrained by the templates of simpler website builders. It includes Webflow AI features that assist with copy generation, layout suggestions, and image creation.</p><p>Webflow occupies a specific niche: more powerful and design-flexible than Squarespace or Wix, but less engineering-intensive than custom code development. It competes most directly with Framer and — at the enterprise level — with custom CMS implementations.</p>`,
        how_it_works: `<p>Designers build websites in Webflow's visual Designer, which maps directly to CSS properties and HTML structure. Interactions and animations are configured visually through the Webflow Interactions panel. The CMS allows structured content to populate dynamic collection pages. Sites are published to Webflow's hosting or exported as clean code for self-hosting. Webflow AI assists within the editor for copy drafting and design suggestions.</p>`,
        workflows: [
            { title: 'Agency Client Website Production', description: 'Web design agencies build and hand off complex marketing websites to clients using Webflow\'s editor, where clients can manage CMS content without requiring developer access.' },
            { title: 'Marketing Site with CMS', description: 'Marketing teams build the site design in Webflow and populate blog posts, case studies, or product pages through the Webflow CMS without touching code.' },
            { title: 'Interactive Page Design', description: 'Designers produce websites with scroll animations, hover interactions, and micro-effects using Webflow\'s visual interaction builder without custom JavaScript.' },
            { title: 'E-Commerce Store Design', description: 'Businesses use Webflow\'s e-commerce features to build custom-designed online stores with full design control over product and checkout pages.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Visual no-code page designer', 'CSS and HTML code export', 'CMS for structured content', 'Interactions and animation editor', 'Webflow hosting with CDN'] },
            { group: 'Advanced Capabilities', items: ['Webflow AI for copy and image generation', 'E-commerce features', 'Memberships and gated content', 'Marketplace of templates', 'API and zapier integrations'] }
        ],
        best_for: ['Professional web designers building client sites', 'Agencies needing scalable website production', 'Marketing teams managing content-heavy sites', 'Businesses requiring custom design beyond template limits', 'Teams wanting clean exportable code from a visual editor'],
        pros: ['Full visual design control without code constraints', 'Clean code output that can be exported and self-hosted', 'CMS is well-suited for blogs, case studies, and collections', 'Large template and community ecosystem', 'Capable interactions and animation system without JavaScript'],
        cons: ['Steeper learning curve than simpler builders', 'Designer pricing is per seat and can be expensive for agencies', 'CMS has data limits on lower plans', 'E-commerce capabilities are less full-featured than Shopify', 'Performance optimisation requires careful site architecture'],
        pricing_overview: `<p>Webflow pricing has two layers: Workspace plans (billed per editor, covering design and project management) and Site plans (billed per published site, covering hosting and CMS data limits). A free plan allows building and staging with Webflow subdomain. Paid site plans add custom domains, form submissions, and higher CMS limits. e-commerce plans add transaction fees and store features.</p>`,
        comparison_summary: `<p>Webflow and Framer are the two dominant professional no-code design platforms. Framer is preferred for motion and animation-first design work. Webflow has a more mature CMS and stronger agency and e-commerce use case coverage. For simpler sites, Squarespace and Wix are more accessible. For shops specifically, Shopify outperforms Webflow e-commerce. Webflow differentiates on the breadth of its CMS, design control, and the exportable code output that reduces long-term platform dependency risk.</p>`
    },

    'firefliesai': {
        long_description: `<p>Fireflies.ai is an AI meeting assistant that joins online meetings to record, transcribe, and summarise conversations. It integrates with video conferencing platforms including Zoom, Google Meet, Microsoft Teams, and Webex, and automatically creates searchable transcripts and AI-generated summaries with action items after meetings.</p><p>Fireflies is designed for sales, recruiting, and business teams that have high meeting volumes and need structured records of conversations for follow-up, coaching, and knowledge retention. It also offers CRM integrations to push meeting data directly into Salesforce, HubSpot, and other systems.</p><p>It competes directly with Otter.ai and tl;dv in the AI meeting transcription category, with a particular strength in its CRM integration and sales team use cases.</p>`,
        how_it_works: `<p>Users connect Fireflies to their conferencing tools and calendar. An AI assistant (Fred) automatically joins scheduled meetings and records audio, then generates a transcript and summary after the meeting ends. The transcript is searchable, with speaker labels and timestamps. AI analysis highlights action items, decisions, and questions. Integrated with CRM tools, Fireflies can auto-push meeting notes and follow-up tasks directly into sales or recruitment workflows.</p>`,
        workflows: [
            { title: 'Sales Call Documentation and CRM Sync', description: 'Sales teams use Fireflies to automatically transcribe customer calls and sync meeting notes, action items, and deal updates directly into Salesforce or HubSpot.' },
            { title: 'Recruiting Interview Records', description: 'Recruiting teams capture and document candidate interviews, making them searchable for recall, comparison, and compliance purposes.' },
            { title: 'Meeting Action Item Tracking', description: 'Operations teams review Fireflies summaries post-meeting to extract and assign action items without replaying recordings or reviewing full transcripts.' },
            { title: 'Coaching and Call Review', description: 'Sales managers use Fireflies\' search and filter tools to review specific moments across meeting recordings — objections raised, competitor mentions, or pricing discussions.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Automatic meeting transcription', 'Speaker identification and labels', 'AI meeting summary and action items', 'Searchable transcript archive', 'Zoom, Meet, Teams, Webex integration'] },
            { group: 'Advanced Capabilities', items: ['CRM integration (Salesforce, HubSpot)', 'Conversation intelligence filters', 'Topic tracking across meetings', 'API access for custom integrations', 'Team workspace and analytics'] }
        ],
        best_for: ['Sales teams documenting customer calls', 'Recruiting teams capturing interview records', 'Operations teams tracking meeting outputs', 'Sales managers reviewing call quality', 'Teams requiring CRM-integrated meeting data'],
        pros: ['Strong CRM integration for sales and recruiting workflows', 'Searchable across all past meeting transcripts', 'Automatic meeting join requires minimal setup', 'Topic and keyword tracking enables coaching use cases', 'Integrates with virtually all major conferencing platforms'],
        cons: ['Automatic joining requires prior notification in some jurisdictions', 'Transcription accuracy affected by audio quality and accents', 'Privacy and consent considerations for recorded meetings', 'Free plan is limited in transcription hours', 'AI summary quality varies with meeting structure'],
        pricing_overview: `<p>Fireflies.ai offers a free plan with limited monthly transcription minutes and basic features. Pro plans increase transcription limits, add full AI analysis, CRM integrations, and conversation intelligence features. Business and Enterprise plans add advanced analytics, higher storage, and team management. Billing is per seat on monthly or annual terms.</p>`,
        comparison_summary: `<p>Fireflies.ai competes most directly with Otter.ai, tl;dv, and Fathom. Otter focuses more on real-time transcription with broad use cases. tl;dv targets video meeting clips for sharing specific moments. Fathom is free for individuals with strong ease of use. Fireflies differentiates on its CRM integration depth, sales team focus, and ability to search and filter across large meeting archives.</p>`
    },

    'capcut': {
        long_description: `<p>CapCut is a free video editing application developed by ByteDance, the company behind TikTok. It is available on mobile and desktop and has grown into one of the most-used video editing tools globally, particularly among social media creators producing short-form content for TikTok, Instagram, and YouTube.</p><p>CapCut includes a range of AI-powered features integrated into the editing workflow, including AI background removal, AI-powered video effects, text-to-speech, auto captions with styling, and script-to-video generation. These features lower the barrier to producing polished video content for non-professional editors.</p><p>CapCut's strength is its combination of no-cost access, deep TikTok social layer integration, and a comprehensive AI feature set that makes polished mobile and short-form video production accessible to anyone with a phone.</p>`,
        how_it_works: `<p>Users import video clips, images, and audio into the CapCut timeline editor on mobile or desktop. AI features are accessible through dedicated menus — auto captions generate and sync subtitles from audio, AI background removal isolates subjects, and template-based editing allows users to apply viral editing styles to their footage. Script-to-video takes written content and generates a video with AI-selected visuals, voiceover, and captions. Finished videos can be exported and published directly to social platforms.</p>`,
        workflows: [
            { title: 'Short-Form Social Video Editing', description: 'Creators edit TikTok and Instagram Reels content in CapCut using music sync, effects, and templates designed for short-form video engagement patterns.' },
            { title: 'Auto Caption Generation', description: 'Content producers add styled, animated captions to videos automatically from audio using CapCut\'s AI transcription, without manually timing text.' },
            { title: 'Script-to-Video Content', description: 'Marketers type or paste a script and use CapCut\'s AI to generate a video with relevant visuals, voiceover, and captions for social platforms.' },
            { title: 'Background Removal for Talking Head Videos', description: 'Creators use AI background removal to replace video backgrounds without a green screen, enabling polished studio-style production from any environment.' }
        ],
        feature_groups: [
            { group: 'Core Editing', items: ['Multi-track video timeline editing', 'Music library and audio tools', 'Transitions and effects library', 'Text and sticker overlays', 'Mobile and desktop versions'] },
            { group: 'AI Features', items: ['Auto captions with styling', 'AI background removal', 'Script-to-video generation', 'AI video effects and filters', 'Text-to-speech narration'] }
        ],
        best_for: ['Social media creators on TikTok and Instagram', 'Marketers producing short-form video content', 'Beginners learning video editing', 'Content teams needing fast turnaround on social video', 'Creators wanting AI features without a paid subscription'],
        pros: ['Free with a comprehensive feature set', 'Deep TikTok integration and trending template access', 'Strong AI features for a no-cost tool', 'Mobile-first with a capable desktop version', 'Auto captions save significant editing time'],
        cons: ['ByteDance ownership raises data privacy concerns in some markets', 'Less capable for long-form professional video production', 'Watermark on some export options requires workarounds', 'Advanced features require CapCut Pro', 'Reliance on TikTok ecosystem may not suit all brand contexts'],
        pricing_overview: `<p>CapCut is free for all basic and most AI features. CapCut Pro removes export watermarks, unlocks more effects and templates, and provides access to additional AI tools at a monthly or annual subscription price. The free tier includes a substantial tool set sufficient for social media content production.</p>`,
        comparison_summary: `<p>CapCut competes with InVideo, Clipchamp, and Adobe Premiere Rush in the consumer video editing space. For social-first short-form content, CapCut's trends and templates library (tied to TikTok) is a unique advantage. Adobe Premiere Rush and Elements are more professional but paid. InVideo focuses more on marketing video templates and AI generation. CapCut differentiates on price (free) and mobile-first social content optimisation.</p>`
    },

    'salesforce-einstein': {
        long_description: `<p>Salesforce Einstein is the AI capability layer embedded across the Salesforce platform, including Sales Cloud, Service Cloud, Marketing Cloud, and Commerce Cloud. It delivers AI-powered features including predictive lead scoring, automated case classification, smart email personalisation, recommendation engines, and generative AI through Einstein GPT.</p><p>Einstein is not a standalone product — it is a platform-level AI capability that surfaces intelligence and automation within the tools Salesforce customers already use. This embedded model means its value is proportional to an organisation's depth of Salesforce adoption and data quality within the platform.</p><p>Enterprise organisations with significant Salesforce investment use Einstein to drive sales productivity, service efficiency, and marketing relevance without adopting separate AI point solutions for each use case.</p>`,
        how_it_works: `<p>Einstein features appear contextually within Salesforce interfaces. In Sales Cloud, predictive lead scores are displayed on lead records based on CRM engagement and demographic data. In Service Cloud, case classification routes tickets based on AI-detected intent. Einstein GPT surfaces generative features such as email draft suggestions in Outlook integrations, service reply recommendations in cases, and code generation in Apex. Administrators configure Einstein feature activation and training preferences in the Salesforce setup menu.</p>`,
        workflows: [
            { title: 'Predictive Lead Scoring for Sales', description: 'Sales teams prioritise outreach using Einstein Lead Scoring, which ranks leads by predicted conversion likelihood based on historical CRM data patterns.' },
            { title: 'Automated Case Routing in Service Cloud', description: 'Customer service teams use Einstein Classification to automatically assign incoming cases to appropriate queues based on content and intent, reducing manual triage.' },
            { title: 'AI-Generated Sales Email Drafts', description: 'Account executives use Einstein GPT to generate personalised outreach email drafts based on CRM contact history and opportunity data.' },
            { title: 'Product Recommendation for Commerce', description: 'E-commerce teams use Einstein Recommendations to personalise product displays for individual shoppers based on browsing and purchase history.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Predictive lead and opportunity scoring', 'Case classification and routing', 'Next best action recommendations', 'Analytics and insight generation', 'Product recommendations'] },
            { group: 'Einstein GPT Capabilities', items: ['Generative email draft suggestions', 'Service reply recommendations', 'Flow generation from natural language', 'Apex code generation', 'Personalised marketing content'] }
        ],
        best_for: ['Enterprise Salesforce customers across Sales and Service clouds', 'Sales operations teams optimising pipeline prioritisation', 'Customer service organisations with high case volumes', 'Marketing teams leveraging CRM data for personalisation', 'IT teams extending Salesforce with low-code AI features'],
        pros: ['Embedded across the Salesforce platform — no separate tool adoption needed', 'Uses existing CRM data for model training relevance', 'Broad coverage across Sales, Service, Marketing, and Commerce use cases', 'Backed by Salesforce\'s enterprise security and compliance infrastructure', 'Einstein GPT enables generative features within existing workflows'],
        cons: ['Value depends heavily on CRM data quality and completeness', 'Requires existing Salesforce licences — not available standalone', 'Advanced Einstein features may require add-on licensing', 'AI model transparency is limited compared to custom ML solutions', 'Vendor lock-in within the Salesforce ecosystem'],
        pricing_overview: `<p>Salesforce Einstein features are included at different levels across Sales Cloud, Service Cloud, and Marketing Cloud plan tiers. Some Einstein features (such as basic scoring) are included in standard plans, while advanced Einstein capabilities and Einstein GPT features may require add-on licences. Enterprise Einstein pricing is typically negotiated as part of overall Salesforce agreement terms.</p>`,
        comparison_summary: `<p>Salesforce Einstein competes with HubSpot AI and Microsoft Dynamics 365 AI in the CRM AI space. HubSpot AI targets mid-market companies with a simpler and lower-cost alternative. Microsoft Dynamics AI integrates closely with Azure ML and Microsoft 365 data. Einstein's advantage is its deep integration across the full Salesforce product suite and the data advantage that comes from the world's most widely adopted CRM platform.</p>`
    },

    'leonardo-ai': {
        long_description: `<p>Leonardo AI is a creative AI platform focused on image generation, with a particular emphasis on game assets, character design, and consistent visual style. It is distinct from general image generators in that it provides tools for training fine-tuned models on user-uploaded reference images, enabling consistent character and object appearance across generated outputs.</p><p>The platform is used by game developers, artists, and creative teams who require visual consistency across a body of work — a challenge with prompt-only image generators where characters and styles can drift between generations.</p><p>Leonardo AI offers real-time generation and canvas editing features alongside its standard generation workflow, making it a more complete creative tool than simple text-to-image platforms.</p>`,
        how_it_works: `<p>Users generate images from text prompts or optionally upload reference images for use with trained models. The platform offers multiple featured model options with different aesthetic styles, as well as the ability to train custom models on uploaded reference datasets. A real-time generation mode produces images as the user types, enabling rapid visual exploration. The AI Canvas allows image editing, outpainting, and compositing within the browser. Generated images can be downloaded or shared.</p>`,
        workflows: [
            { title: 'Consistent Character Design Across Assets', description: 'Game developers train a custom Leonardo model on a character design, then generate multiple poses, expressions, and environments featuring that consistent character.' },
            { title: 'Game Environment and Asset Generation', description: 'Artists generate tilesets, environment concepts, and item designs at speed using Leonardo\'s game-oriented model presets.' },
            { title: 'Style-Locked Illustration Series', description: 'Illustrators train a fine-tuned model on their own artistic references and generate a consistent series of images in that style without prompt drift.' },
            { title: 'Real-Time Creative Exploration', description: 'Designers use Leonardo\'s real-time generation mode to explore visual directions as they adjust their prompt description interactively.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Text-to-image generation', 'Multiple featured model presets', 'Custom model training on uploaded images', 'Real-time generation mode', 'Image-to-image transformation'] },
            { group: 'Advanced Capabilities', items: ['AI Canvas for editing and outpainting', 'Motion (image animation)', '3D texture generation', 'ControlNet for pose reference', 'API access for developers'] }
        ],
        best_for: ['Game developers generating consistent character and world assets', 'Concept artists exploring visual styles', 'Illustrators producing series with consistent style', 'Creative studios requiring fine-tuned brand-specific models', 'Developers integrating image generation into workflows via API'],
        pros: ['Custom model training enables consistent character appearance', 'Game-specific presets produce relevant art styles', 'Real-time generation accelerates visual exploration', 'Relatively generous free credit model', 'API access for programmatic integration'],
        cons: ['Custom model training has a learning curve', 'Total credit system can be confusing', 'Advanced capabilities require paid subscription or credits', 'Less strong for photorealistic versus stylised outputs', 'Community features can make the interface feel cluttered'],
        pricing_overview: `<p>Leonardo AI offers a free plan with a daily token allocation for image generation. Paid plans increase monthly token allocation, priority access to featured models, and commercial usage rights. Custom model training, higher resolution generation, and API access are available on higher tiers. Plans are billed monthly or annually.</p>`,
        comparison_summary: `<p>Leonardo AI competes with Midjourney, Stable Diffusion, and Adobe Firefly in the image generation space. Midjourney produces more artistically polished output but offers no fine-tuning. Stable Diffusion matches Leonardo in fine-tuning capability but requires self-setup. Adobe Firefly targets professional commercial workflows with Creative Cloud integration. Leonardo differentiates on being accessible via web browser with built-in custom model training — a combination not offered by most alternatives.</p>`
    },

    'invideo': {
        long_description: `<p>InVideo is an AI-powered video creation platform that enables users to produce marketing videos, social content, and explainer videos from text scripts or AI-generated content. It provides a large library of customisable templates and an AI workflow that converts a topic or script into a complete video with selected footage, voiceover, captions, and background music.</p><p>InVideo is used by marketers, content creators, and businesses that need to produce video content at volume without specialist video production skills or expensive software. Its AI-driven workflow makes it particularly accessible for teams producing frequent social or marketing video output.</p><p>InVideo competes primarily with Pictory and Lumen5 in the AI script-to-video category, positioning itself as a more feature-complete platform with broader template and media library options.</p>`,
        how_it_works: `<p>Users select a workflow — script to video, article to video, or AI-generated from a topic — and InVideo generates a video draft with suggested footage clips, a voiceover (AI-generated or text-to-speech), captions, and background music. Users can edit individual scenes, swap media, adjust timing, and customise text within InVideo's browser-based editor. Finished videos are rendered and exported or shared directly to social platforms.</p>`,
        workflows: [
            { title: 'Blog-to-Video Content Repurposing', description: 'Content teams paste article URLs or text into InVideo and generate a social-ready video summarising the article\'s key points with relevant footage.' },
            { title: 'Social Media Ad Creation', description: 'Marketing teams use InVideo templates to produce platform-specific ad videos for Facebook, Instagram, and YouTube from product briefs.' },
            { title: 'Explainer and Product Videos', description: 'Businesses generate explainer videos with AI voiceover from product descriptions or script outlines, without video production overhead.' },
            { title: 'YouTube Channel Content', description: 'Content creators produce regular YouTube videos from scripted topics using InVideo\'s AI generation and editing tools.' }
        ],
        feature_groups: [
            { group: 'Core Capabilities', items: ['Script-to-video generation', 'Template library (6,000+ templates)', 'AI voiceover generation', 'Auto captions', 'Stock media library (iStock and Shutterstock integration)'] },
            { group: 'Advanced Capabilities', items: ['AI topic-to-video generation', 'Brand kit with custom colours and fonts', 'Screen recording integration', 'Team collaboration features', 'Multi-platform export presets'] }
        ],
        best_for: ['Marketing teams producing social and ad video content', 'Content creators repurposing text content into video', 'Small businesses producing product and explainer videos', 'Social media managers maintaining video publishing schedules', 'Agencies producing video for multiple clients at scale'],
        pros: ['Large template library for rapid video production', 'AI topic and script to video reduces production friction significantly', 'Stock media integration avoids separate asset sourcing', 'Multi-platform export presets', 'Accessible for non-video professionals'],
        cons: ['Output quality depends on template and stock media selection', 'Final videos require editing to avoid generic appearance', 'AI voiceover quality varies by language and style', 'Free plan has watermark on exports', 'Less suitable for narrative or documentary video production'],
        pricing_overview: `<p>InVideo offers a free plan with limited exports and InVideo watermark on output. Paid plans remove the watermark, increase export limits, expand the media library access, and unlock team features. Business plans add team collaboration and higher storage. Pricing is per account on monthly or annual billing.</p>`,
        comparison_summary: `<p>InVideo competes with Pictory and Lumen5 in the AI script-to-video space. Pictory is better known for video repurposing from long-form content. Lumen5 targets social media video with a simpler interface. InVideo offers a broader feature set including editing, templates, and media library depth. For motion and AI avatar-based video, Synthesia and HeyGen are different category tools targeting different production needs.</p>`
    }

};

let patched = 0;
const modified = [];
for (const tool of tools) {
    if (enrichment[tool.id]) {
        Object.assign(tool, enrichment[tool.id]);
        patched++;
        modified.push(tool.id);
    }
}
writeFileSync(PATH, JSON.stringify(tools, null, 2));
console.log(`Batch 5 complete. Patched ${patched} tools: ${modified.join(', ')}`);
